### ISSUE TITLE
Setting up a plugin repository

### ISSUE THREAD

**Issue by SphinxC0re** [mc-server/MCServer#1023]
What if we set up such a repository like the one that bukkit has? It would be easier for the users to find and/or upload plugins. We could also run this under another url like `plugins.mc-server.org`

**Comment by NiLSPACE** [comment]
Bringing this issue back:
@FakeTruth tried to create a plugin repo quite a while back, but he stopped working on it. He still has the 'preview' online: http://pluginsold.mc-server.org/ What I really like with this version is that you can login using your forum username and password.

**Comment by FakeTruth** [comment]
Syncing with the forums is really easy :)

**Comment by tigerw** [comment]
![1](https://cloud.githubusercontent.com/assets/2939130/5994093/008f00e4-aa5f-11e4-8b1c-53a3825e7f35.png)
![2](https://cloud.githubusercontent.com/assets/2939130/5994094/009115fa-aa5f-11e4-92be-8ea181a6cea7.png)
![3](https://cloud.githubusercontent.com/assets/2939130/5994095/009b34cc-aa5f-11e4-91bb-df9e6048d381.png)
![4](https://cloud.githubusercontent.com/assets/2939130/5994096/00a2f450-aa5f-11e4-9cfe-2518ebbbbb59.png)

**Comment by tigerw** [comment]
*crickets*

**Comment by tigerw** [comment]
Classic MCS developers' response (or lack thereof) :P

**Comment by NiLSPACE** [comment]
I have to admit that it looks pretty good :D

**Comment by SphinxC0re** [comment]
Yeah it does :+1:

**Comment by bearbin** [comment]
Are you going to put the code up tiger?

**Comment by tonibm19** [comment]
So beutiful

**Comment by tigerw** [comment]
Very relieved you like it. I'll upload the code when its more presentable :)

**Comment by tigerw** [comment]
Code is uploaded. Want to try adding plugins?

**Comment by bearbin** [comment]
I tried :P

**Comment by bearbin** [comment]
It seems quite good, but a bit buggy.

**Comment by SphinxC0re** [comment]
For me, too. but the design is a little chabby :)

**Comment by tigerw** [comment]
Chabby?

**Comment by bearbin** [comment]
Closing. Plugin repo now exists in a usable state, and further development can be focused there.

**Comment by NiLSPACE** [comment]
I dissagree. It's not fully implemented and tested, and we might want to change the place it's hosted.

**Comment by bearbin** [comment]
It's open source, so anyone can host it. 

Anyway, this proposal was just for having one, not choosing between different ones if they are available. Now there is one there isn't much point in this proposal anymore.

**Comment by tonibm19** [comment]
@NiLSPACE
Also, it could be in another URL such as plugins.mc-server.org

**Comment by NiLSPACE** [comment]
@tonibm19 Yes, that's what I meant.

**Comment by SphinxC0re** [comment]
@FakeTruth mapped that to my devilbyte server :)

**Comment by tigerw** [comment]
And the funny thing is, despite the language flamewar at the beginning, the repository ended up being written in PHP, interfaced to SQL Server, run on Internet Information Services (8), and hosted on an Azure instance running Windows Server.

lel.

**Comment by SphinxC0re** [comment]
I agree, it's a total mess :wink:

**Comment by mathwhiz1212** [comment]
I would suggest scaleway for hosting: https://www.scaleway.com/ I use the cheapest BareMetal server. (The C1.) for hosting my cuberite server. It's 2.99 euros a month.
