### ISSUE TITLE
Animals walk and swim far too fast.

### ISSUE THREAD

**Issue by bearbin** [mc-server/MCServer#1065]
Animals walk at about the speed of creative flight, and when punched go almost out of render distance.

Animals also swim super fast.

**Comment by SafwatHalaby** [comment]
Is this still relevant?

**Comment by zackp30** [comment]
I hit a sheep, and it didn't try to go to space ==> bug fixed. :smiley:

**Comment by SafwatHalaby** [comment]
Swimming speed is normal too, closing.
