### ISSUE TITLE
Pathfinding doesn't work in water

### ISSUE THREAD

**Issue by Masy98** [mc-server/MCServer#1220]
I've continued working on the knockback and i noticed that the pathfinding function doesn't work in/under water. They keep missing the block they "targetted" so they float endless in circles because they are trying to get to there target.

**Comment by SafwatHalaby** [comment]
The PathFinder has been [completely changed](http://forum.mc-server.org/showthread.php?tid=1571), water works now, and it will be tweaked and improved later.
