### ISSUE TITLE
Segfault?

### ISSUE THREAD

**Issue by bearbin** [mc-server/MCServer#1225]
http://ci.bearbin.net/job/MCServer%20Linux-x86-64/2114/console

**Comment by tigerw** [comment]
I read somewhere between the creation of this issue and now that GCC 4.9, which I think was the compiler version used here, will aggressively remove null pointer checks (see flag `-fno-delete-null-pointer-checks `). This may have been the cause?

One description of it:
https://deepthought.isc.org/article/AA-01167/0/Operational-Notification-Changes-in-gcc-Code-Optimization-Can-Cause-a-Crash-in-BIND.html

**Comment by worktycho** [comment]
Its unlikely as coverity gives us warnings when a null check is unnecessary.

**Comment by madmaxoft** [comment]
Is this even still an issue?
