### ISSUE TITLE
Many bugs

### ISSUE THREAD

**Issue by maniak89** [mc-server/MCServer#131]
videos (52 bugs):
http://www.youtube.com/playlist?list=PLn5aAow3Nf0W8bBls4Xvy__hkxyySZZiu

Crash servers:

    core.4924
    https://mega.co.nz/#!T0pj2TwT!FeTe_yixGq3HwNzc0UrtBDRh0X8YAqBU3cvYL8maol4
    Spawn mob on y==0 cors
    #0  0x00007ffff6e0a037 in raise () from /lib/x86_64-linux-gnu/libc.so.6
    #1  0x00007ffff6e0d698 in abort () from /lib/x86_64-linux-gnu/libc.so.6
    #2  0x00007ffff6e02e03 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
    #3  0x00007ffff6e02eb2 in __assert_fail () from /lib/x86_64-linux-gnu/libc.so.6
    #4  0x00000000005a083f in cChunk::GetBlock (this=0x7fffbc592900, a_RelX=3, a_RelY=-2, a_RelZ=14) at source/Chunk.cpp:2225
    #5  0x0000000000639d70 in cPickup::Tick (this=0x7fffe0a970d0, a_Dt=50, a_Chunk=...) at source/Entities/Pickup.cpp:87
    #6  0x000000000059b3a4 in cChunk::Tick (this=0x7fffbc592900, a_Dt=50) at source/Chunk.cpp:463
    #7  0x0000000000778022 in cChunkMap::cChunkLayer::Tick (this=0x7fffd800a4a0, a_Dt=50) at source/ChunkMap.cpp:2321
    #8  0x000000000077783b in cChunkMap::Tick (this=0xf01070, a_Dt=50) at source/ChunkMap.cpp:2161
    #9  0x00000000006f8159 in cWorld::Tick (this=0x7ffff5656010, a_Dt=50) at source/World.cpp:610
    #10 0x00000000006f4e6e in cWorld::cTickThread::Execute (this=0x7ffff5dd0298) at source/World.cpp:219
    #11 0x0000000000737d52 in cIsThread::thrExecute (a_Param=0x7ffff5dd0298) at source/OSSupport/IsThread.h:73
    #12 0x00007ffff71a2f8e in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
    #13 0x00007ffff6ecce1d in clone () from /lib/x86_64-linux-gnu/libc.so.6

    core.5547
    https://mega.co.nz/#!foxBCTbC!a7cyzhGOtrn8Crmqe5Fj6BO_P60lZEExkHWcKG11ilY
    #0  0x00007ffff6e0a037 in raise () from /lib/x86_64-linux-gnu/libc.so.6
    #1  0x00007ffff6e0d698 in abort () from /lib/x86_64-linux-gnu/libc.so.6
    #2  0x00007ffff6e02e03 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
    #3  0x00007ffff6e02eb2 in __assert_fail () from /lib/x86_64-linux-gnu/libc.so.6
    #4  0x0000000000641655 in ClickActionToString (a_ClickAction=3556772800) at source/Defines.h:180
    #5  0x000000000063e580 in cClientHandle::HandleWindowClick (this=0x7fffe0000a60, a_WindowID=5 '\005', a_SlotNum=41, a_ClickAction=3556772800, a_HeldItem=...) at source/ClientHandle.cpp:1060
    #6  0x0000000000616f5a in cProtocol150::ParseWindowClick (this=0x7fffd4000b70) at source/Protocol/Protocol15x.cpp:130
    #7  0x000000000061bf3c in cProtocol125::ParsePacket (this=0x7fffd4000b70, a_PacketType=102 'f') at source/Protocol/Protocol125.cpp:1072
    #8  0x000000000062072a in cProtocol132::ParsePacket (this=0x7fffd4000b70, a_PacketType=102 'f') at source/Protocol/Protocol132.cpp:510
    #9  0x0000000000617e09 in cProtocol161::ParsePacket (this=0x7fffd4000b70, a_PacketType=102 'f') at source/Protocol/Protocol16x.cpp:228
    #10 0x000000000061baea in cProtocol125::DataReceived (this=0x7fffd4000b70, a_Data=0x7fffee7fb9f0 "f\005", a_Size=12) at source/Protocol/Protocol125.cpp:1012
    #11 0x000000000061f2dc in cProtocol132::DataReceived (this=0x7fffd4000b70, a_Data=0x7fffdc000a98 "sj\362`S\237\253\233{\215\071&", a_Size=12) at source/Protocol/Protocol132.cpp:193
    #12 0x00000000006250f8 in cProtocolRecognizer::DataReceived (this=0x7fffe0010ce0, a_Data=0x7fffdc000a98 "sj\362`S\237\253\233{\215\071&", a_Size=12)
        at source/Protocol/ProtocolRecognizer.cpp:90
    #13 0x000000000063f39d in cClientHandle::Tick (this=0x7fffe0000a60, a_Dt=50) at source/ClientHandle.cpp:1427
    #14 0x00000000006f90e1 in cWorld::TickClients (this=0x7ffff5656010, a_Dt=50) at source/World.cpp:890
    #15 0x00000000006f817c in cWorld::Tick (this=0x7ffff5656010, a_Dt=50) at source/World.cpp:612
    #16 0x00000000006f4e6e in cWorld::cTickThread::Execute (this=0x7ffff5dd0298) at source/World.cpp:219
    #17 0x0000000000737d52 in cIsThread::thrExecute (a_Param=0x7ffff5dd0298) at source/OSSupport/IsThread.h:73
    #18 0x00007ffff71a2f8e in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
    #19 0x00007ffff6ecce1d in clone () from /lib/x86_64-linux-gnu/libc.so.6

    core.5606
    https://mega.co.nz/#!XhATiAxb!adBlXQhaD430mSXvpCpn4wjOhMgtUNE-yFL16fdBbgM
    y>=256
    #0  0x00007ffff6e0a037 in raise () from /lib/x86_64-linux-gnu/libc.so.6
    #1  0x00007ffff6e0d698 in abort () from /lib/x86_64-linux-gnu/libc.so.6
    #2  0x00007ffff6e02e03 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
    #3  0x00007ffff6e02eb2 in __assert_fail () from /lib/x86_64-linux-gnu/libc.so.6
    #4  0x00000000005a083f in cChunk::GetBlock (this=0x7fffd413ff00, a_RelX=0, a_RelY=256, a_RelZ=12) at source/Chunk.cpp:2225
    #5  0x0000000000773dc5 in cChunkMap::GetBlock (this=0xf01d10, a_BlockX=0, a_BlockY=256, a_BlockZ=12) at source/ChunkMap.cpp:1072
    #6  0x00000000006fad51 in cWorld::GetBlock (this=0x7ffff5656010, a_X=-96, a_Y=256, a_Z=124) at source/World.cpp:1426
    #7  0x000000000063da00 in cClientHandle::HandlePlaceBlock (this=0x7fffe0000a70, a_BlockX=-96, a_BlockY=256, a_BlockZ=124, a_BlockFace=1 '\001', a_CursorX=4,     a_CursorY=16, a_CursorZ=4, 
        a_ItemHandler=...) at source/ClientHandle.cpp:875
    #8  0x000000000063d73a in cClientHandle::HandleRightClick (this=0x7fffe0000a70, a_BlockX=-96, a_BlockY=255, a_BlockZ=124, a_BlockFace=1 '\001', a_CursorX=4,     a_CursorY=16, a_CursorZ=4, 
        a_HeldItem=...) at source/ClientHandle.cpp:810
    #9  0x0000000000620a2d in cProtocol132::ParseBlockPlace (this=0x7fffd400c4c0) at source/Protocol/Protocol132.cpp:540
    #10 0x000000000061bd0b in cProtocol125::ParsePacket (this=0x7fffd400c4c0, a_PacketType=15 '\017') at source/Protocol/Protocol125.cpp:1053
    #11 0x000000000062072a in cProtocol132::ParsePacket (this=0x7fffd400c4c0, a_PacketType=15 '\017') at source/Protocol/Protocol132.cpp:510
    #12 0x0000000000617e09 in cProtocol161::ParsePacket (this=0x7fffd400c4c0, a_PacketType=15 '\017') at source/Protocol/Protocol16x.cpp:228
    #13 0x000000000061baea in cProtocol125::DataReceived (this=0x7fffd400c4c0, a_Data=0x7fffee7fb9f0 "\v\300Xy\214\217\272p\337@p\a?\254:", a_Size=258) at source/Protocol/Protocol125.cpp:1012
    #14 0x000000000061f2dc in cProtocol132::DataReceived (this=0x7fffd400c4c0, 
        a_Data=0x7fffdc000b08 "u\321\r\324\035<Kj\363]\340\334G\261\fw0\332q\342\362\030\337 \315\366\236\376\"\365\255O\312oA\f?\245l\323\177\257_nQ}\022\271\026\244,\264\203\367\360\325\375\070\303\300\fM\301\272\360\b\f\363g\236\037\301\351\377Ago\326A[\352\233\345?z/-\022\326\335Y0\036\262u~f\"63\251\234U\005\367\025R\204\070\203\255\362\234P(\234/\305\062 \355\203\356!O\001[\002\177\351\306|\300\235A\312\351Q>\314K?\326$\354\255\376\237\315\017\222\274\024\027\302f\324x\025?\256\210p\031\224\377I\213\270\326\372Xt.4\273\267\307\v<I\025\004r\310\355\270lN\001\266\236_,\321\337A\200"..., a_Size=258) at source/Protocol/Protocol132.cpp:193
    #15 0x00000000006250f8 in cProtocolRecognizer::DataReceived (this=0x7fffe0010cf0, 
        a_Data=0x7fffdc000b08 "u\321\r\324\035<Kj\363]\340\334G\261\fw0\332q\342\362\030\337 \315\366\236\376\"\365\255O\312oA\f?\245l\323\177\257_nQ}\022\271\026\244,\264\203\367\360\325\375\070\303\300\fM\301\272\360\b\f\363g\236\037\301\351\377Ago\326A[\352\233\345?z/-\022\326\335Y0\036\262u~f\"63\251\234U\005\367\025R\204\070\203\255\362\234P(\234/\305\062 \355\203\356!O\001[\002\177\351\306|\300\235A\312\351Q>\314K?\326$\354\255\376\237\315\017\222\274\024\027\302f\324x\025?\256\210p\031\224\377I\213\270\326\372Xt.4\273\267\307\v<I\025\004r\310\355\270lN\001\266\236_,\321\337A\200"..., a_Size=258) at source/Protocol/ProtocolRecognizer.cpp:90
    #16 0x000000000063f39d in cClientHandle::Tick (this=0x7fffe0000a70, a_Dt=50) at source/ClientHandle.cpp:1427
    #17 0x00000000006f90e1 in cWorld::TickClients (this=0x7ffff5656010, a_Dt=50) at source/World.cpp:890
    #18 0x00000000006f817c in cWorld::Tick (this=0x7ffff5656010, a_Dt=50) at source/World.cpp:612
    #19 0x00000000006f4e6e in cWorld::cTickThread::Execute (this=0x7ffff5dd0298) at source/World.cpp:219
    #20 0x0000000000737d52 in cIsThread::thrExecute (a_Param=0x7ffff5dd0298) at source/OSSupport/IsThread.h:73
    #21 0x00007ffff71a2f8e in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
    #22 0x00007ffff6ecce1d in clone () from /lib/x86_64-linux-gnu/libc.so.6

**Comment by tigerw** [comment]
Well, not *all* the bugs in that video are fixed.

**Comment by worktycho** [comment]
No but the issue is basically useless, as we can't partially close it.

**Comment by tigerw** [comment]
I agree.
