### ISSUE TITLE
Implementing Pathfinding

### ISSUE THREAD

**Issue by wiseoldman95** [mc-server/MCServer#1391]
Edit: Pathfinding was implemented and is now in master.

Update 2: PR #1916

Update: For those of you not following the forums, work on this has resumed, the code is here:
https://github.com/wiseoldman95/MCServer/tree/pathfindingReborn
For details, see the forums: http://forum.mc-server.org/showthread.php?tid=1571

_____Old post:

I expect a long discussion, so the main thread is at the forums: http://forum.mc-server.org/showthread.php?tid=1571
I suggest to discuss it there only, this is just a "bridge" between Github and that thread. For the purpose of referencing etc.

**Comment by wiseoldman95** [comment]
Sorry for the delay guys, life changed and I had to delay this. I am still planning to do it though. I don't want to promise a date, but work will probably resume in March / April.

**Comment by tigerw** [comment]
It's perfectly okay, no apology warranted :)

**Comment by wiseoldman95** [comment]
Update: For those of you not following the forum, work on this has resumed, the code is here:
https://github.com/wiseoldman95/MCServer/tree/pathfindingReborn
For details, see the forum: http://forum.mc-server.org/showthread.php?tid=1571

**Comment by wiseoldman95** [comment]
PR https://github.com/mc-server/MCServer/pull/1916

**Comment by wiseoldman95** [comment]
Pathfinding was merged, closing.
