### ISSUE TITLE
Improve test coverage

### ISSUE THREAD

**Issue by worktycho** [mc-server/MCServer#1403]
At the moment our test coverage is abysmal (<1%) we should improve that by writing more tests.

Current coverage: [![Coverage Status](https://img.shields.io/coveralls/mc-server/MCServer.svg)](https://coveralls.io/r/mc-server/MCServer?branch=master)

**Comment by tigerw** [comment]
![i-thought-this-cake-day-thing-was-supposed-to-be-easy-28484](https://cloud.githubusercontent.com/assets/2939130/7690607/f538285a-fdac-11e4-9397-3d664a528bed.jpg)

**Comment by worktycho** [comment]
Pretty much. The project need a lot of restructuring before test are really useful.
