### ISSUE TITLE
HOOK_PLAYER_SPAWNED doesn't get called if player has been moved to world

### ISSUE THREAD

**Issue by Seadragon91** [mc-server/MCServer#1435]
Hey,

I am not sure if that is a bug.
There is a hook named HOOK_PLAYER_SPAWNED, that gets called if the player (re)spawns in the world where they are.

My thought is, if I move the player with the function Player:MoveToWorld("world"), then the hook HOOK_PLAYER_SPAWNED should be called, but that doesn't happen.

There is no other hook with that I can check if the player gets added to the world, for the function Player:MoveToWorld("world")

Thanks,
Seadragon91

**Comment by Seadragon91** [comment]
I completely miss a hook that will get called, when the player has moved to a other world. Should I add a own hook like HOOK_PLAYER_CHANGED_WORLD or should we changed the behavior of MoveToWorld. At the moment MoveToWorld will only call the hook if the boolean ShouldSendRespawn is true.

**Comment by NiLSPACE** [comment]
A simple OnEntityChangingWorld and OnEntityChangedWorld in cWorld::MoveToWorld should do the trick.

**Comment by Seadragon91** [comment]
Could make a pull request for it, should I?

**Comment by madmaxoft** [comment]
Yes please.
