### ISSUE TITLE
Plugin channel (BungeeCord teleporting)

### ISSUE THREAD

**Issue by misiek08** [mc-server/MCServer#1441]
Hello!
I saw that BungeeCord integration is done now, but I have one more question (problem?) to solve. BC uses own "channel" to make possible teleport players. More about usage here: http://www.spigotmc.org/wiki/bukkit-bungee-plugin-messaging-channel/
Is it possible to use it in MCS? Can you provide few-lines Lua example?

**Comment by misiek08** [comment]
Is this solved in core or just not going to fix it server-side?

**Comment by madmaxoft** [comment]
You said in your last comment that you got it working, so I assumed this issue is no longer necessary.

**Comment by misiek08** [comment]
Ok. It's just workaround, but ok - it works some way.
