### ISSUE TITLE
A scheduled task can crash server on reload command

### ISSUE THREAD

**Issue by Seadragon91** [mc-server/MCServer#1556]
Hey,

I started an scheduler that runs 600 ticks later. If I do an reload, the server crashes directly (relase version) or in  a few seconds (debug version) with that error:

[7f1b379f5700|22:36:52] Assertion failed: IsValid(), file /home/lukas/cpp/MCServer/src/Bindings/LuaState.cpp, line 290
MCServer_debug: /home/lukas/cpp/MCServer/src/Bindings/LuaState.cpp:290: bool cLuaState::PushFunction(int): Assertion `0' failed.

Reproduce:
1) Create a scheduled code that will run for example 600 ticks later
2) Run the command /reload directly after step 1
3) Server should crash (can take a few seconds in debug version) 

Good luck by fixing.

regards,
Seadragon91

**Comment by madmaxoft** [comment]
I have implemented this for the scheduled task. I added a new interface class, `cPluginLua::cResettable`, that stores a pointer to the plugin and its mutex, and has a `Reset` function. Once the plugin is unloaded, it marks all instances of this class as "reset", which effectively nullifies the pointer inside them. Now the only change required in the scheduled tasks was to lock the mutex and check whether the plugin pointer is valid.
