### ISSUE TITLE
Various runtime failures with terrain at Y=255

### ISSUE THREAD

**Issue by madmaxoft** [mc-server/MCServer#1606]
When a generator generates terrain at Y=255, various things break at runtime, hitting assertions and sometimes even crashes.

We should try running the server with a flat height generator set to 255 and fix all the failures.

**Comment by tommysanterre** [comment]
I'm interested in fixing this, it could be a good way to get an overview of the codebase. How can I run the server with a flat height generator?

**Comment by madmaxoft** [comment]
I've outlined the necessary steps in the forum reply: http://forum.mc-server.org/showthread.php?tid=1771&pid=18248#pid18248

**Comment by tommysanterre** [comment]
I have trouble understanding the issue, I hit assertion in get block methods that verify the requested block in within limit which I think is correct. 

I created worlds with various flat heights with all finalizer and I get worlds that I would consider invalid but I think that is also correct.

Example worlds:
http://i.imgur.com/CpGlOos.png
http://i.imgur.com/cyWIhOo.png

If you could provide me a world.ini file that has the problem it would make it really easy to understand the issue.

**Comment by madmaxoft** [comment]
The assertion is exactly what this issue is about - find code in the generator that produces invalid block coord accesses. Typical example - the grass finisher would place a tall grass block on top of grass blocks. But if the grass block was at Y=255 ,the tall grass block would go above the chunk top, so the generator needs to check against this.

**Comment by tommysanterre** [comment]
Perfect I will look into that.

**Comment by tommysanterre** [comment]
I think I found the problem. There is a lot of code testing for the height but the test sometimes use y < Height and sometime y <= Height. 

I propose we create utility methods in cChunkDef to test if a coordinate is valid so we use the same test everywhere. This will eliminate code duplication at the same time. 

By making the Width and Height private i'm pretty confident I can find all these duplicate tests.

    static bool IsMoreThanChunkHeight(int v)
    {
        return v >= Height;
    }

    static bool IsLessThanChunkHeight(int v)
    {
        return v < 0;
    }

    static bool IsValidHeight(int v)
    {
        return !IsMoreThanChunkHeight(v) && !IsLessThanChunkHeight(v);
    }

    static bool IsMoreThanChunkWidth(int v)
    {
        return v >= Width;
    }

    static bool IsLessThanChunkWidth(int v)
    {
        return v < 0;
    }

    static bool IsValidWidth(int v)
    {
        return !IsMoreThanChunkWidth(v) && !IsLessThanChunkWidth(v);
    }

    static bool IsValidCoordinates(int x, int y, int z)
    {
        return IsValidWidth(x) && IsValidHeight(y) && IsValidWidth(z);
    }

    static void AssertCoordinatesIsValid(int x, int y, int z)
    {
        ASSERT((!IsLessThanChunkWidth(x)) && (!IsMoreThanChunkWidth(x)));
        ASSERT((!IsLessThanChunkHeight(y)) && (!IsMoreThanChunkHeight(y)));
        ASSERT((!IsLessThanChunkWidth(z)) && (!IsMoreThanChunkWidth(z)));
    }

**Comment by madmaxoft** [comment]
The different tests are because the code sometimes tests coords of the neighbor, rather than the block being set. For example the door placement code checks the block being clicked, which is the one below the new door, and it also needs to check two blocks above, so the comparison is slightly different for those. (Of course the actual code is a bit different, but I guess you get the point)

I think the methods you propose are an overkill, there is very little code outside of `cChunkDef` that could use those.

**Comment by tommysanterre** [comment]
I believe there is more use of that constant to test limits than you realize. I found 123 use of the Height constant using those regex 
">=* cChunkDef::Height"
"<=* cChunkDef::Height"

I have pasted the result in a gist:
https://gist.github.com/tommysanterre/4a43ae892bfbebe0a416

Maybe the width methods are not as useful, I put them in for consistency and readability.

I believe we can fix a lot of off by one errors doing this change and also prevent future mistakes. We could investigate each case and make the code clearer. I corrected an assertion in monster.cpp by changing a < to <=. In that specific case it really made sense that this was the problem. It's actually the only assert I managed to hit so far.

https://github.com/tommysanterre/MCServer/commit/707cae4a3232dcdf8c4b6c89cfa61a083d902654

**Comment by madmaxoft** [comment]
As you can see exactly in the commit you linked, the function will not help much there, it would result in extra calculations being done and thus the code might get less readable after the change.

Give it a try for a few cases and post a PR with the results, so that we can judge the change in effect.

**Comment by tommysanterre** [comment]
I submitted a new pull request, however I still can't generate a world with a height of 255. I would need help to fix that problem. My changes were tested with a world of height 0, 1, 253 and 254. There are still some errors logged by some method that automatically adjust the coordinates requested to valid ones.

**Comment by madmaxoft** [comment]
That would be because you clipped the `cBlockArea`; I've commented in the PR.

**Comment by tommysanterre** [comment]
I made changes based on your comments but I still can't create a world with height = 255.

**Comment by tommysanterre** [comment]
@madmaxoft could you help me figure out why I can't generate a world with height=255. I had another look and i'm not progressing on my own. Currently to find the problem all I can think of is look at every reference to the cChunkDef::Height constant and inspect the surrounding code. I managed to find a few problems that I fixed in my pull request but not this one.

**Comment by madmaxoft** [comment]
You might want to instead try stepping through the generator code to see where the height is getting lost. Start in the `cHeiGenFlat::GenHeightMap()` ($/src/Generating/HeiGen.cpp:21), whether it has the proper height set, then step on from there. The generator should first generate the heightmap, then based on it, generate the shape (a "map" of voxel -> density for the entire chunk), from there the composition (density is changed into particular blocks - air, grass, dirt etc.). The composition is already using a `cBlockArea` object inside the `cChunkDesc` class, so you can insert some debugging code to save that block area into a file, so that you can inspect it with external tool.

**Comment by tommysanterre** [comment]
Thanks @madmaxoft I was able to find the bug with your help.

It was a char overflow. Do we have something to detect overflow in debug. We use a typedef for HEIGHTTYPE which is the type that had an overflow. Maybe we could replace the typedef in debug with a class that wrap an int and assert that we don't overflow. 

There could be other hard to find cases like this one. I would be interested in writing that if you think it would be useful for the project.

**Comment by worktycho** [comment]
A better way would be to compile the project under clangs -fsanitize=signed-integer-overflow and -fsanitize=unsigned-integer-overflow which inserts runtime checks for overflow. It would be really interesting to see the result of running the project under -fsanitize=undefined which includes -fsanitize=signed-integer-overflow and a load of other undefined behavior checkers.

**Comment by tommysanterre** [comment]
That's interesting, I didn't know it was possible. I will have a look.

**Comment by tommysanterre** [comment]
Unfortunately char are not supported by the overflow check only int. I still ran the code with the checks enabled.

I believe it would be a good idea to create an issue to inspect the errors found, there is a lot of them but they are not related to the issue i'm trying to solve.

https://gist.github.com/tommysanterre/59350aa90a9bbc2082cf

**Comment by worktycho** [comment]
Thanks for the gist. I'll triage them.

**Comment by tommysanterre** [comment]
I couldn't find any other case HEIGHTTYPE overflow, I believe this issue is done.

**Comment by madmaxoft** [comment]
So did you manage to get the full-height terrain from the generator?

**Comment by tommysanterre** [comment]
Yes I did

**Comment by madmaxoft** [comment]
I guess this is finished, then :)

**Comment by tommysanterre** [comment]
:)
