### ISSUE TITLE
Server crashes on loading world

### ISSUE THREAD

**Issue by Seadragon91** [mc-server/MCServer#1658]
Hey,

I started the server and stopped the server and on next start it crashes on loading a chunk.
The zip file contains the world, the gdb.txt and the log file. It not happens with other fresh generated worlds. This is the seed of the world 839147298
https://dl.dropboxusercontent.com/u/72700534/crash_11.12.2014.zip

Hope that are enough informations to find and fix the problem.

Good luck,
Seadragon91

**Comment by NiLSPACE** [comment]
Can we close this? I think @madmaxoft fixed it some time ago.

**Comment by Seadragon91** [comment]
Okay, I close this. I am unable to reproduce the crash anymore.
