### ISSUE TITLE
Disconnected when setting up a command block

### ISSUE THREAD

**Issue by carc1n0gen** [mc-server/MCServer#1692]
When I try to create a simple command block I get disconnected and the command in the block doesn't save.

**Comment by carc1n0gen** [comment]
I am very new to github and pretty much only used it for a few little things of my own.  This was the first project on github I felt like contributed to so I don't know how it all works so I am sorry if it is wrong to ask.  Is this issue being looked in to?  I have confirmed the problem to happens in both the precompiled linux 64 bit build and by compiling myself, and precompiled Windows 64 bit build.

**Comment by madmaxoft** [comment]
I confirm the bad behavior, when a client edits the commandblock's text and hits the Done button, the server kicks them (and commits suicide in Debug mode due to badly parsed PluginMessage packet).

**Comment by madmaxoft** [comment]
Fixed by ignoring the garbage data at the end of the packets.

**Comment by Pokechu22** [comment]
FYI, for the command block it isn't garbage data but instead an extra Boolean for whether output from the command block should be stored (which is why it initially happened).  Don't know about what it is in 1.7.10, though.

**Comment by tigerw** [comment]
Thanks, added the missed read.
