### ISSUE TITLE
Bug while opening door with non-empty hand

### ISSUE THREAD

**Issue by SphinxC0re** [mc-server/MCServer#1694]
Setting up door works fine. But you can't open them with something in your hand:

### Before ###

![2014-12-30_14 07 40](https://cloud.githubusercontent.com/assets/3702016/5578743/a54d481c-902d-11e4-903b-6dfa9e461003.png)

### Block setting down ###

![2014-12-30_14 07 56](https://cloud.githubusercontent.com/assets/3702016/5578745/b44777c0-902d-11e4-8215-e22040e2cfd4.png)

### removing the Block ###

![2014-12-30_14 08 09](https://cloud.githubusercontent.com/assets/3702016/5578748/bfe92c2c-902d-11e4-9a7a-4713569d9402.png)

after destroying the rest of the door, the door seems to disappear and randomly appears again in my inventory.

**Comment by gurugeek42** [comment]
Some more information: turns out this bug only applies if the door has a block above it.

**Comment by madmaxoft** [comment]
That might be a good lead. Thanks for the report.

**Comment by madmaxoft** [comment]
Not only does it need to have a block above it, the block above it needs to be present before the door is placed. weird weird weird.

**Comment by madmaxoft** [comment]
Ah, simple, it's because the server doesn't place the door, while the client thinks the door is placed. So there's two issues:
- why doesn't the server place the door
- why doesn't the server report correctly that the door wasn't placed?

**Comment by madmaxoft** [comment]
Fixed in b165ab63633cd8c45d505a2fd2165807ea2b50ec
