### ISSUE TITLE
Too many single-type hostile mobs

### ISSUE THREAD

**Issue by BlahBlahBlase** [mc-server/MCServer#1699]
I just build my first MCServer and in the world I generated, the only hostile mobs are creepers, and lots of them. I went into the world.ini and removed creepers from the animals list but now there are no hostile mobs spawning. Is this a common problem?

**Comment by BlahBlahBlase** [comment]
update: So I switched the game difficulty in the world.ini file to peaceful then tried to change it back in the in game command console, which didn't change it back. I changed it in the world.ini file but now I just have tons of skeletons spawning and nothing else.

**Comment by madmaxoft** [comment]
Wow, that's weird. I haven't seen such behavior; but then I don't use the server on survival.

**Comment by hirnwunde** [comment]
Same here.
A lot of creepers, no spiders, zombies or skelletons.
Build was made today from git-repository.

**Comment by BlahBlahBlase** [comment]
its definitely frustrating. Redstone contraptions such as powered rails don't work either.

**Comment by jsebean** [comment]
Same issue here. Anybody aware of a work around or should monsters just be disabled?

**Comment by Knochi** [comment]
Same here, 
Downloaded Binary for Raspberry Pi last week.
Besides many mobs are spawning in the water (I'll do an extra Bugreport for that)
![2015-02-19_14 26 57](https://cloud.githubusercontent.com/assets/5979046/6267389/c4d7b026-b843-11e4-929c-084ee513d635.png)

**Comment by BlahBlahBlase** [comment]
Yeah I sorta gave up on MCServer because of this. It makes survival no fun at all. Plus I figured out how to get spigot running solid on a RPi 2.

**Comment by jsebean** [comment]
Send me an email (jonah@jsebean.com) on your Spigot details. I ran a Spigot
build and it was too laggy on my Pi 2. It's off topic though here so you
can send an email if you are kind and wish to :)

On Thu, Feb 19, 2015 at 1:53 PM, BlahBlahBlase <notifications@github.com>
wrote:

> Yeah I sorta gave up on MCServer because of this. It makes survival no fun
> at all. Plus I figured out how to get spigot running solid on a RPi 2.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/mc-server/MCServer/issues/1699#issuecomment-75101335>.
>



-- 
God Bless,
Jonah Sabean
http://www.jsebean.com/

**Comment by madmaxoft** [comment]
I believe I have fixed this, but it won't help with existing chunks, it will only affect newly spawned entities.

**Comment by jsebean** [comment]
Awesome. Thank you much. Will be building now :P

On Fri, Feb 20, 2015 at 5:56 PM, Mattes D <notifications@github.com> wrote:

> I believe I have fixed this, but it won't help with existing chunks, it
> will only affect newly spawned entities.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/mc-server/MCServer/issues/1699#issuecomment-75326495>.
>



-- 
God Bless,
Jonah Sabean
http://www.jsebean.com/

**Comment by Knochi** [comment]
Ok works, but now lots of monsters spawn.
I think there are different possibilities for different monster types to spawn. Is there something documented in original MC?
For example i had 2 enderman, 2 spiders and 4 zombies in the first minute!
All running after me, but not doing any harm?
![2015-02-21_13 50 40](https://cloud.githubusercontent.com/assets/5979046/6314141/6b9153ac-b9d1-11e4-947d-6f27598c7aca.png)
Sorry but this is not a survival mode...

**Comment by madmaxoft** [comment]
That would be the crude AI we have - it simply tells all nearby mobs to go to you no matter what.

**Comment by jsebean** [comment]
But the wont attack? I thought they use to?

On Sat, Feb 21, 2015 at 9:14 AM, Mattes D <notifications@github.com> wrote:

> That would be the crude AI we have - it simply tells all nearby mobs to go
> to you no matter what.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/mc-server/MCServer/issues/1699#issuecomment-75371171>.
>



-- 
God Bless,
Jonah Sabean
http://www.jsebean.com/

**Comment by tigerw** [comment]
The code for attacking is there, but doesn't produce very consistent results. If you stay close to the hostile mob/stay still, they should deal damage?

**Comment by Knochi** [comment]
Unfortunatly they don't. Anyhow the behaviour ist strange. 
For example you can see the spiders jumping at you, but they don't deal any damage.
Beside the jump lasts seconds and looks more like the spider is getting weightless for a few seconds.

**Comment by jsebean** [comment]
So TLDR: the AI needs a lot of work :P

On Sat, Feb 21, 2015 at 1:32 PM, Knochi <notifications@github.com> wrote:

> Unfortunatly they don't. Anyhow the behaviour ist strange.
> For example you can see the spiders jumping at you, but they don't deal
> any damage.
> Beside the jump lasts seconds and looks more like the spider is getting
> weightless for a few seconds.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/mc-server/MCServer/issues/1699#issuecomment-75382291>.
>



-- 
God Bless,
Jonah Sabean
http://www.jsebean.com/

**Comment by SphinxC0re** [comment]
@jsebean YES :dancer:
