### ISSUE TITLE
Periodic full source tarballs

### ISSUE THREAD

**Issue by linnemannr** [mc-server/MCServer#1703]
I'm trying to author a FreeBSD port for MCServer, but the use of submodules in the git tree makes source tarballs from codeload incomplete. Could the entire source tree with submodules be periodically packaged and published in the releases or on the build server, so there is a complete and authoritative source tarball on the web that can be fetched?

**Comment by madmaxoft** [comment]
What exactly does "author a FreeBSD port" mean? Are there changes that need to be made in order to make MCS work on FreeBSD? Why can't you simply pull everything via git and build?

Don't get me wrong, I believe source packages are necessary, but I don't see a point of making them until we have a proper release cycle; doing them for each nightbuild seems somewhat space-wasting.

**Comment by bearbin** [comment]
I'll set up a source download tarball for you. But yes, why is not not possible to use git during the build process for the port?

**Comment by bearbin** [comment]
Source build is up and running.

http://builds.cuberite.org/job/MCServer%20source/

**Comment by linnemannr** [comment]
A FreeBSD port is how software packages are built for FreeBSD (see https://www.freebsd.org/ports/) It typically consists of a makefile that directs the port system on how to fetch the software source (distfile) and build it, an associated checksum for the distfile, any freebsd specific patches that must be applied, a packaging list, and other things of that nature. The current state of github integration in the FreeBSD ports tree (via bsd.sites.mk) retrieves source tarballs from codeload.github.com with the fetch utility, and that tarball omits git submodules that are required for the build. I'm not aware of any support in the ports system for using git itself to clone the repo and produce the distfile.

One source package available on github would be sufficient for my immediate needs until you guys work out a release cycle, the port does not need to be the bleeding edge of the source code. Nightlies are certainly not warranted, and the data returned via the URL must be invariant. The latest official source package here on github is just far too old (circa MC 1.6).

Thank you for your assistance! I'm looking forward to getting MCServer up and running in my jails and getting the port out to the general FreeBSD audience.

**Comment by worktycho** [comment]
Its probably inadvisable to try and pick a particular release as MCServer operates on a rather extreme from of continuous deployment at the moment where only the trunk is really supported. The release on github is only a marker to where we dropped support for Minecraft 1.6. 

However if you want any help interacting with our build system I'm happy to help. You may in particular want to look at the undocumented build options, MCSERVER_BUILD_ID, MCSERVER_BUILD_SERIES_NAME, MCSERVER_BUILD_DATETIME and MCSERVER_BUILD_COMMIT_ID, which are provided for package maintainers to supply the version info.

**Comment by linnemannr** [comment]
That's still okay, though, I can apply deltas through port patches as needed for bugfixes, etc. I don't see what you are suggesting with the build system, however.

**Comment by linnemannr** [comment]
didn't mean to close issue

**Comment by worktycho** [comment]
cmake accepts parameters during the build through `-D<Parameter name>=<value>` syntax. We have a few custom ones for adding version information to released executables. It helps us track where an executable came from if someone posts to the forums for help. MCSERVER_BUILD_ID is an arbitrary string you can use to identify the package version. MCSERVER_BUILD_SERIES_NAME should be set to a value to indicate that the executable came from your package. MCSERVER_BUILD_DATETIME should be set to the date of the build or creation of the package, its your choice. And MCSERVER_BUILD_COMMIT_ID should be the commit the package was created from. They will be used to build a string that goes into the log at startup.

**Comment by worktycho** [comment]
Having a look at the FreeBSD docs, you probably want to set MCSERVER_BUILD_ID to the value of PORTVERSION.

**Comment by linnemannr** [comment]
Oh yes, I see. I will definitely use those in the port. Thanks for the tip! My intention was to set PORTVERSION to the version of the MC server API supported by the distribution, but that may be inappropriate.

**Comment by worktycho** [comment]
Setting the PORTVERSION to the API version would be slightly difficult as we don't have version numbers for the API. Also it would probably be a good idea to have separate version for bug fixes even if they don't change the API.

**Comment by linnemannr** [comment]
That can be solved by PORTREVISION, and I typically see that in practice. The package name is composited as ${PORTNAME}-${PORTVERSION}${PORTREVISION:+_${PORTREVISION}}, e.g. MCServer-1.8.1_1.

I might be able to use the 7 digit github commit id associated with the 

My intent until the project decides on a release cycle and version scheme is simply to capture the version of the Minecraft client supported. If you have another preference, I will abide by that.

I don't know, maybe it doesn't make sense for me to try to push for a port I can upstream at this time. maybe I should experiment with a custom do-extract target that uses git to fetch the full source tree and just leave it at that for my own purposes for now.

**Comment by worktycho** [comment]
That makes perfect sense. I thought you were referring to our plugin API. We generally talk about the minecraft version as the protocol version.

**Comment by linnemannr** [comment]
Great. Now as for that source tarball, I'll just fetch it from the jenkins build artifacts for the MCServer Source project bearbin was kind enough to set up. Is that correct? It looks like that project monitors the git repo, is that correct?

**Comment by worktycho** [comment]
It should do.

**Comment by bearbin** [comment]
Yep. It creates a new tarball for every commit.

It only keeps 20 of them around though, but that should be ok.

On 14 January 2015 at 23:46, worktycho <notifications@github.com> wrote:

> It should do.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mc-server/MCServer/issues/1703#issuecomment-70015794>.
>



-- 

Alexander Harkness (bearbin)
Find my GPG key on the Ubuntu Keyserver - http://keyserver.ubuntu.com:11371/

**Comment by madmaxoft** [comment]
Can we close this report now?
