### ISSUE TITLE
MCServer User Guide

### ISSUE THREAD

**Issue by hendrikyoda** [mc-server/MCServer#1704]
The User Guide about the compiling the server on your own is wrong/incomplete. 
As a new user it was hard to solve the problem.
Managed to do it with: https://github.com/mc-server/MCServer-docker

Maybe just add this to the user guide or link it.

**Comment by bearbin** [comment]
Where is the user guide you are talking about. We have several.

**Comment by hendrikyoda** [comment]
It is this User guide: http://book.mc-server.org/
It's linked on the homepage mc-server.org.

**Comment by bearbin** [comment]
Ok. It has it's own repo, moving issue.

**Comment by bearbin** [comment]
Moved to https://github.com/mc-server/mcs-book/issues/6
