### ISSUE TITLE
Too many leave block changes

### ISSUE THREAD

**Issue by Howaner** [mc-server/MCServer#1714]
Currently the server sends too many leave block changes.

The server updates the meta from a leave block every tick.
It's important to change this. (Don't change the meta or don't send it to the client)

This generates many lags in 1.7 and in 1.8 with disabled VBO.

**Comment by madmaxoft** [comment]
This should be rather easy, there's already code in `cChunk::FastSetBlock()` that filters out changes in the meta for liquid blocks, so just add a proper condition for leaves there.
