### ISSUE TITLE
Force ipv4 in server config?

### ISSUE THREAD

**Issue by TrevorHarrison** [mc-server/MCServer#1723]
When I try to connect to the server it fails to open the port.

"netstat -anp" shows:

tcp6       0      0 :::25565                :::*                    LISTEN      30672/./MCServer

If I use ssh to port forward to the server's 25565, I can connect to localhost:25565 and it works.

I don't want to have to deal with ipv6 firewall configs and dns values.  Is there a way to force the server to listen to a specific address, and specifically a ipv4 address?

**Comment by madmaxoft** [comment]
There's no plan for supporting specific interfaces (there's no multiplatform way of enumerating them); the server should now listen on all interfaces on a dual-stack socket (both IPv4 and IPv6) where available, and on single-stack addresses elsewhere. If you have IPv4 enabled, you should be able to connect to the IPv4 address without any problem, even when netstat shows you that the socket is `tcp6`.
