### ISSUE TITLE
HTTP cannot listen on port after server restart

### ISSUE THREAD

**Issue by madmaxoft** [mc-server/MCServer#1726]
@XsFrozdY initially reported:
Also sometimes when restarting the server I get: `HTTP server error on port 8080:10048 <cannot bind IPv6 socket to port 8080  <normally only one user allowed for each socket adress<protocol/networkadress/port>` or something like that, I translated some of it from swedish

It seems that either the HTTP server doesn't have the REUSE flag set, or there is some other difference from the main server, which didn't get reported.

**Comment by madmaxoft** [comment]
This doesn't happen for me, neither on Windows (7 Pro, x64) nor Ubuntu (desktop 14.04, x86).
Is there anyone who can reproduce this issue?

**Comment by Howaner** [comment]
I can reproduce this with the server port:
```[21:38:24] Cannot listen on port 25565: 98 (Cannot bind IPv6 socket to port 25565: 98 (Address already in use)).```

**Comment by madmaxoft** [comment]
Well then, it's your lucky day, you get to fix this :)

**Comment by XsFrozdY** [comment]
Well it happened on Win7 Ulti x64, I think it is when you restart the server and you're logged into the web admin still and have auto-login it happens, not sure though.
