### ISSUE TITLE
Server doesn't recognizes when players leave beds before it gets day

### ISSUE THREAD

**Issue by Masy98** [mc-server/MCServer#1728]
I discoverd some weird bed behavior:
First off, you can break a single piece of a bed with a piston but the other bed-part is still placed (kinda expected that to happen).
But where it gets weird is, when sleeping in it and leaving it before it gets day, the server seems to think that a player is still in that bed, so it recognizes that bed as "occupied". But only the part of the bed you clicked on when you went to sleep is occupied, not the other one. When you break one of the pieces, the other will be still placed (maybe because they are now to diffrent blocks that do not belong to each other).
Here is a video that should explain it a bit better:
https://www.youtube.com/watch?v=_BXrDC1oQKk&feature=youtu.be

**Comment by worktycho** [comment]
@tigerw sounds like an issue with your pistion code.

**Comment by Masy98** [comment]
wow, i'm kinda new to uploading videos, is it normal that it takes so long to process a video?

**Comment by Masy98** [comment]
video is ready now, not in HD though...
