### ISSUE TITLE
Server crash - cWSSAnvil::cMCAFile::GetChunkData

### ISSUE THREAD

**Issue by Kretol** [mc-server/MCServer#1730]
Not sure what is causing this, but over the past few days something has caused a crash several times.  I never saw this message before because I didn't have a batch file running to just restart the server.  Now I do and can see the error message to report it!

Running MCServer Windows x64-# 163.

![crashmsg](https://cloud.githubusercontent.com/assets/916825/6095540/4875cd46-af16-11e4-84d0-3bdbd2378a80.png)

https://app.box.com/s/29rx48b71ei232m73yqy6wmfrqzzbuv0

**Comment by madmaxoft** [comment]
I'm wondering how this could happen. Is the world generated by MCServer, or did you copy it from a Vanilla or a Bukkit server?

The problem is that the data for the chunk really is corrupt - the entire chunk's datastream has been replaced with all zeroes.

**Comment by madmaxoft** [comment]
Ah, found it. Turns out there was a loophole when the server actually did overwrite the next chunk with the data of the previous chunk.

Unfortunately, your data is already corrupt and there is nothing we can do to restore the missing chunk. I'll try to salvage the rest of the chunks from the file, at least.

**Comment by madmaxoft** [comment]
Here's the salvaged file:
http://mc-server.xoft.cz/salvaged%201730/

**Comment by Kretol** [comment]
For reference, I had indeed copied the world from a Forge server that had been up for a few days.  A few folks had been building in it for a bit (after moving it to MCServer), and then I also helped out with performing a few WorldEdit operations to clear a large cylinder.
Thank you for your efforts!
