### ISSUE TITLE
Grass doesn't spread.

### ISSUE THREAD

**Issue by bearbin** [mc-server/MCServer#1743]
Forum thread: http://forum.mc-server.org/showthread.php?tid=1782

**Comment by NiLSPACE** [comment]
I can confirm this. I had allot of dirt and placed some grass in it and it didn't grow at all.

**Comment by SphinxC0re** [comment]
That's weird because it did work quite a while ago

**Comment by NiLSPACE** [comment]
Okay. I did some testing, and found out that grass spreading kinda works. Grass does spread down, but it won't spread to a block on the same height or above.

**Comment by SphinxC0re** [comment]
Where is the grass simulator located :dancer:

**Comment by jsebean** [comment]
I am also affected by this issue. Gass was not growing. Using build #13 for ARM Linux on a Raspberry Pi 2 ARMv7 system.

**Comment by NiLSPACE** [comment]
@SphinxC0re It's in `src/Blocks/BlockDirt.h`

**Comment by SphinxC0re** [comment]
Okay. I'll try to fix this
