### ISSUE TITLE
Array for storing Players?

### ISSUE THREAD

**Issue by Sulfatezzz** [mc-server/MCServer#1746]
Whats about a array where the Server stores Players? Would be great for Plugin Devs.

**Comment by bearbin** [comment]
What about the players, just names, player objects, or what?

Names would be quite easy, but player objects wouldn't be possible due to threading.

**Comment by NiLSPACE** [comment]
I don't think that's possible due to multithreading.

You can use 
```lua
cRoot:Get():ForEachPlayer(
   function(a_Player)
      -- Stuff
   end
)
```

**Comment by Sulfatezzz** [comment]
I started learning c++ a while ago and come from PHP and was wondering if storing player objects in an array where Possible like in php for things like teleporting all Players to an special place...

**Comment by bearbin** [comment]
You'd use the API functions using callbacks like cWorld:ForEachPlayer(function...)

AFAIK (I haven't checked the docs)

**Comment by madmaxoft** [comment]
You need to use the callbacks, because, due to multithreading, there's no guarantee that if you store the object and later use it, that it will still be valid. The player may have disconnected in the meantime, a mob may have despawned, etc. That's why you need to use the callbacks.

**Comment by Sulfatezzz** [comment]
And why you wont implemt an Vector to MCServer?

**Comment by madmaxoft** [comment]
I've just explained why any access to players MUST go through callbacks instead of any kind of an array / vector. And for a generic vector, use Lua tables. So what is it that you want?
