### ISSUE TITLE
MCServer(PE)

### ISSUE THREAD

**Issue by Sulfatezzz** [mc-server/MCServer#1749]
Hey,
I have a idea for this Project. Whats About to wirte MCServerPE?
It would be a Minecraft: Pocket Edtion Server Software written in C++. Currently the only working Server Software for PE ist Pocketmine-MP in PHP but it has many bugs/many things are not implemented...

It would be great if someone would make this Project.

About MCPE:

Its the Mobile Version of Minecraft written in c++. Its still in Alpha but month for month there comes Updates.

**Comment by tigerw** [comment]
Need more developers for that, unfortunately.

**Comment by Sulfatezzz** [comment]
I would help. I'm currently learning C++ and have currently time to make a Server Software

**Comment by tonibm19** [comment]
That would be awesome. I thought about that too. Imagine a C++ universal server :D

**Comment by Sulfatezzz** [comment]
I know this 2 Projects. I would use for the Protocol Raknet. (Pocketmine is using it too)
If you and @tigerw or Other Developer of the Project are intrested to create a C++ Server Software would be this Awesome.

**Comment by worktycho** [comment]
This is not an appropriate place to recruit developers. It might be worth posting in the [forum](http://forum.mc-server.org/forumdisplay.php?fid=10).

**Comment by tonibm19** [comment]
:(

**Comment by tonibm19** [comment]
Well, I'm interested, but I don't think I'm capable of doing that.
As worktycho said, forum?

**Comment by tigerw** [comment]
Tycho: ![Get outta here](http://media-cache-ec0.pinimg.com/236x/0f/ca/a1/0fcaa17087aab6379697a399f8bf3cc8.jpg)

**Comment by tonibm19** [comment]
Haha, you read my mind xD.
The discussion was interesting.
But well, he's right, this is not the right place.

**Comment by Sulfatezzz** [comment]
[Created] http://forum.mc-server.org/showthread.php?tid=1792&pid=18475#pid18475
