### ISSUE TITLE
C Methodes ins C++?

### ISSUE THREAD

**Issue by Sulfatezzz** [mc-server/MCServer#1752]
Hey,
I was wondering why MCServer use for the Logger function printf instead cout....
Can you please explain why?

**Comment by NiLSPACE** [comment]
Because you can format a string with printf
```cpp
printf ("Characters: %c %c \n", 'a', '65');
```

**Comment by tigerw** [comment]
Would this be the iostream equivalent?
`cout << "Characters: " << 'a' << ' ' << 65 << endl;`

**Comment by madmaxoft** [comment]
Not exactly.
`std::cout << "Characters: " << 'a' << ' ' << static_cast<char>(65) << endl;`

**Comment by tigerw** [comment]
I was under the impression that you could give the stream numbers directly?

**Comment by madmaxoft** [comment]
Yes, but the original code wanted to print a character (`%c`) based on its ascii value (`65`).

**Comment by tigerw** [comment]
Those subtleties.
