### ISSUE TITLE
Add buttons on top and bottom of blocks

### ISSUE THREAD

**Issue by madmaxoft** [mc-server/MCServer#1756]
Currently the button's blockhandler doesn't handle placing buttons on the top and bottom faces of a block (1.8 feature?) Add the handling for those two block faces.

**Comment by NiLSPACE** [comment]
Same for levers. Or was that already implemented in an earlier version of MC.

**Comment by SphinxC0re** [comment]
Levers should work. I tried that a few times

**Comment by alexandreguertin** [comment]
I submitted a pull-request for this issue.

**Comment by alexandreguertin** [comment]
The pull-request has been merged. Should we close this issue?
@madmaxoft
