### ISSUE TITLE
Redstone dust doesn't work properly.

### ISSUE THREAD

**Issue by XsFrozdY** [mc-server/MCServer#1763]
When you have a redstone torch powering a line of redstone dust, after disabling the torch, the dust flashes on and off really fast untill it's nearly shut off, but it doesn't shut off because there's still some dust being powered somehow.

It's hard to explain, you need to try it yourself.

Edit:
the Windows x64 build 178 of the server, and I'm running Windows 7 ulti. x64

**Comment by DevToaster** [comment]
I've also noticed this in both the Linux and Windows builds.  Sometimes when powered by a button and the redstone is stacked using a glowstone tower, the redstone never turns off.

**Comment by XsFrozdY** [comment]
Temporary fix: only use 1 dust, then repeater, then dust and so on, 1 dust works properly.

**Comment by bigbrotherx52** [comment]
Same issue. One thing I've noticed is that the orientation and direction of the redstone might matter. I have 2 simple contraptions, one being the mirror image of the other, and one works and the other doesn't.
