### ISSUE TITLE
Lighting  is wrong, chamber of stone is not absolutely dark.

### ISSUE THREAD

**Issue by joshi07** [mc-server/MCServer#1764]
when i make a solid chamber of Stone, the light can pass through the stone partly. ( Torches )

![unbenannt](https://cloud.githubusercontent.com/assets/10674976/6337015/249f6d6c-bba7-11e4-9936-7ebdce9def11.png)

**Comment by worktycho** [comment]
What does the debug screen read? It might be a renderer bug.

**Comment by joshi07** [comment]
debug screen? i'm sorry which one ? Server ? Client ? and how do i get it ?

**Comment by madmaxoft** [comment]
This is most likely a manifestation of #134 - when you change a block that changes the lightmap, the lightmap invalidation isn't propagated to the neighboring chunks, so when they are reloaded, they get wrong lighting.

**Comment by madmaxoft** [comment]
Closing as duplicate.
