### ISSUE TITLE
Flowing water to still water "endless Well"

### ISSUE THREAD

**Issue by Kellerkind85** [mc-server/MCServer#1783]
If you take a Waterblock out of a 1Block deep Sea, normally the other blocks around should fill up the missing water and become standing water.

Without this also the "endless Well" is not working.

**Comment by bearbin** [comment]
What is the contents of your world.ini file?

**Comment by Kellerkind85** [comment]
Oh.. ok perhaps its my bad. I am Sorry. But thanks for your help. here it is

-------------------------------
-------------------------------
[SpawnProtect]
ProtectRadius=10

[WorldLimit]
LimitRadius=0

[Difficulty]
WorldDifficulty=1

[General]
Dimension=Overworld
IsDaylightCycleEnabled=1
Gamemode=0
Weather=0
TimeInTicks=13403

[Broadcasting]
BroadcastDeathMessages=1
BroadcastAchievementMessages=1

[SpawnPosition]
MaxViewDistance=12
PregenerateDistance=20
X=-611.09742876027
Y=85
Z=1011.5583653016

[Storage]
Schema=Default
CompressionFactor=0

[Plants]
MaxCactusHeight=3
MaxSugarcaneHeight=3
IsCactusBonemealable=0
IsCarrotsBonemealable=1
IsCropsBonemealable=1
IsGrassBonemealable=1
IsMelonStemBonemealable=1
IsMelonBonemealable=0
IsPotatoesBonemealable=1
IsPumpkinStemBonemealable=1
IsPumpkinBonemealable=0
IsSaplingBonemealable=1
IsSugarcaneBonemealable=0

[Physics]
DeepSnow=1
ShouldLavaSpawnFire=1
TNTShrapnelLevel=2
WaterSimulator=Vanilla
LavaSimulator=Vanilla
SandInstantFall=0
RedstoneSimulator=Incremental

[Mechanics]
CommandBlocksEnabled=0
PVPEnabled=1
UseChatPrefixes=1

[Monsters]
VillagersShouldHarvestCrops=1
AnimalsOn=1
Types=bat, cavespider, chicken, cow, creeper, enderman, horse, mooshroom, ocelot, pig, sheep, silverfish, skeleton, slime, spider, squid, wolf, zombie

[LinkedWorlds]
NetherWorldName=world_nether
EndWorldName=world_end

[Generator]
Generator=Composable
BiomeGen=MultiStepMap
ShapeGen=DistortedHeightmap
CompositionGen=DistortedHeightmap
Finishers=Ravines, WormNestCaves, WaterLakes, WaterSprings, LavaLakes, LavaSprings, OreNests, Mineshafts, Trees, Villages, SprinkleFoliage, Ice, Snow, Lilypads, BottomLava, DeadBushes, NaturalPatches, PreSimulator, Animals
BiomeGenCacheSize=64
BiomeGenMultiCacheLength=4
SeaLevel=62
BiomalNoise3DFrequencyX=40.000000
BiomalNoise3DFrequencyY=40.000000
BiomalNoise3DFrequencyZ=40.000000
BiomalNoise3DBaseFrequencyX=40.000000
BiomalNoise3DBaseFrequencyZ=40.000000
BiomalNoise3DChoiceFrequencyX=40.000000
BiomalNoise3DChoiceFrequencyY=80.000000
BiomalNoise3DChoiceFrequencyZ=40.000000
BiomalNoise3DAirThreshold=0.000000
BiomalNoise3DNumChoiceOctaves=4
BiomalNoise3DNumDensityOctaves=6
BiomalNoise3DNumBaseOctaves=6
BiomalNoise3DBaseAmplitude=1.000000
CompositionGenCacheSize=64
WormNestCavesSize=64
WormNestCavesGrid=96
WormNestMaxOffset=32
WaterLakesProbability=25
LavaLakesProbability=10
MineShaftsGridSize=512
MineShaftsMaxOffset=256
MineShaftsMaxSystemSize=160
MineShaftsChanceCorridor=600
MineShaftsChanceCrossing=200
MineShaftsChanceStaircase=200
VillageGridSize=384
VillageMaxOffset=128
VillageMaxDepth=2
VillageMaxSize=128
VillageMinDensity=50
VillageMaxDensity=80
BottomLavaLevel=10
PreSimulatorFallingBlocks=1
PreSimulatorWater=1
PreSimulatorLava=1
HeightGen=DistortedHeightmap
MultiStepMapOceanCellSize=384
MultiStepMapMushroomIslandSize=64
MultiStepMapRiverCellSize=384
MultiStepMapRiverWidth=0.125000
MultiStepMapLandBiomeSize=1024
DistortedHeightmapFrequencyX=10.000000
DistortedHeightmapFrequencyY=10.000000
DistortedHeightmapFrequencyZ=10.000000

[WaterSimulator]
Falloff=1
TickDelay=5
NumNeighborsForSource=2

[LavaSimulator]
Falloff=2
TickDelay=30
NumNeighborsForSource=-1

[FireSimulator]
BurnStepTimeFuel=500
BurnStepTimeNonfuel=100
Flammability=50
ReplaceFuelChance=50000

[Seed]
Seed=361820914

[WaterSprings]
HeightDistribution=0, 0; 10, 10; 11, 75; 16, 83; 20, 83; 24, 78; 32, 62; 40, 40; 44, 15; 48, 7; 56, 2; 64, 1; 255, 0
Chance=24

[LavaSprings]
HeightDistribution=0, 0; 10, 5; 11, 45; 48, 2; 64, 1; 255, 0
Chance=9

[Animals]
AnimalSpawnChunkPercentage=10

**Comment by madmaxoft** [comment]
You're right, indeed it doesn't work. Weird, I was under the impression that this had been implemented. Perhaps it's in the `Floody` simulator only?

**Comment by SphinxC0re** [comment]
[WaterSimulator]
Falloff=1
TickDelay=5
**NumNeighborsForSource=2**

This might be a hint

**Comment by Kellerkind85** [comment]
OK... and.. what should i use here?

**Comment by madmaxoft** [comment]
No, the value is correct. The code handling it seems to be broken.

**Comment by Kellerkind85** [comment]
Some news here?
Can the code handling be fixed?
