### ISSUE TITLE
Lua API: Example for tolua class outdated

### ISSUE THREAD

**Issue by Seadragon91** [mc-server/MCServer#1787]
Hey,

I wanted to test something with mobs, but this example usage is outdated.
http://mc-server.xoft.cz/LuaAPI/tolua.html
Please update it.

Thanks you very much,
Seadragon91

**Comment by NiLSPACE** [comment]
The example would have never worked, because we never had any mob classes exported.

**Comment by Seadragon91** [comment]
Oh well and what i, if I want to color a sheep?
