### ISSUE TITLE
Stack trace will occur on checking if a entity is a mob

### ISSUE THREAD

**Issue by Seadragon91** [mc-server/MCServer#1789]
Hey,

I have here an stack trace that prints this error:
```
[18:34:44] LUA: Plugins/TestPlugin/TestPlugin.lua:15: error in function 'IsMob'.
     argument #1 is 'cArrowEntity'; 'const cEntity' expected.

[18:34:44] Stack trace:
[18:34:44]   [C](-1): IsMob
[18:34:44]   Plugins/TestPlugin/TestPlugin.lua(15): (no name)
[18:34:44] Stack trace end
[18:34:44] Error in plugin TestPlugin calling function <callback>()
```

Here is the TestPlugin:
```lua
function Initialize(Plugin)
    Plugin:SetName("TestPlugin")
    Plugin:SetVersion(1)

    PLUGIN = Plugin

    -- Hooks
    cPluginManager:AddHook(cPluginManager.HOOK_SPAWNING_ENTITY, OnSpawningEntity)

    LOG("Initialised " .. Plugin:GetName() .. " v." .. Plugin:GetVersion())
    return true
end

function OnSpawningEntity(a_World, a_Entity)
    if (a_Entity:IsMob()) then
        print("Is a Mob")
    end
end
```
Reproduce
1. Add this plugin to the server and the name to the settings.ini
2. Start the server
3. Log into the server
4. Shoot with an bow
5. Stack trace will be printed

I already tried to fix it, but I am not good enough in c++

Good luck and thanks for fixing,
Lukas

**Comment by LO1ZB** [comment]
Did you tried to use it without "()"?

**Comment by Seadragon91** [comment]
It's correct, the message "Is a Mob" will be printed for entities that are mobs, but if it reach the entity arrow, the stack trace will be printed. I have found no way to avoid this error.

**Comment by Seadragon91** [comment]
Looks like a caste problem in tolua.

**Comment by Seadragon91** [comment]
Any idea?

**Comment by Seadragon91** [comment]
Closing this as fixed, because of commit
`https://github.com/mc-server/Core/commit/f27efc472b3e8c7802bf5295373f10d90897ebdc`
the line `local Ent = tolua.cast(Entity, "cEntity")` fixes the described above.
Thanks to @jan64

**Comment by NiLSPACE** [comment]
But the code above should work, so there is something wrong in the API. I'm reopening if you don't mind.

**Comment by jan64** [comment]
Call to GetClass on cProjectileEntity descendants
(ex. cExpBottle, cArrow and possibly other non-direct cEntity descendant) fails, 
while working for cEntity and direct cEntity descendants (ex. cExpOrb).

Workaround: mc-server/Core#123

**Comment by madmaxoft** [comment]
I've just tested `cExpBottleEntity` and the `GetClass()` call worked alright:
```
Lua type:        'userdata'
ToLua type:      'cEntity'
GetEntityType(): '9'
GetClass():      'cExpBottleEntity'
```

The test code creates an entity and then queries it using `cWorld:DoWithEntityByID()`, this is the callback:
```lua
function (a_CBEntity)
	LOG("Lua type:        '" .. type(a_CBEntity)           .. "'")
	LOG("ToLua type:      '" .. tolua.type(a_CBEntity)     .. "'")
	LOG("GetEntityType(): '" .. a_CBEntity:GetEntityType() .. "'")
	LOG("GetClass():      '" .. a_CBEntity:GetClass()      .. "'")
end
```

**Comment by madmaxoft** [comment]
Ah, it works in the `cWorld:DoWithEntityByID()` call, but it doesn't work in the `HOOK_SPAWNING_ENTITY` hook callback. For the same callback function used as the hook callback this time, I get this output:
```
New entity is spawning:
  Lua type:        'userdata'
  ToLua type:      'cArrowEntity'
LUA: Plugins/Debuggers/Debuggers.lua:1671: error in function 'GetEntityType'
(+ stacktrace)
```

**Comment by madmaxoft** [comment]
I've just confirmed that ToLua++ only supports one level of inheritance. Just for reference: `debug.getregistry()["tolua_super"][getmetatable(a_CBEntity)]` returns the map of C++ classes (to bool `true`) that `a_CBEntity` descends from; only the top level inheritance is listed.

I might be able to fix this, but it will require quite a lot of digging in ToLua internal sources...

**Comment by Seadragon91** [comment]
Doing a cast of the Entity to the Entity fixes the problem.
```
function OnSpawningEntity(World, Entity)
    local Ent = tolua.cast(Entity, "cEntity")
    if (Ent:IsA("cArrowEntity")) then
        local arrow = tolua.cast(Ent, "cArrowEntity")
        print("arrow.IsCritical = " .. tostring(arrow:IsCritical()))
    end
end
```

**Comment by NiLSPACE** [comment]
Yes, but it's still a bug that it doesn't work without casting.

**Comment by madmaxoft** [comment]
Casting is a bad solution, because tolua casting can convert anything to anything, it doesn't check:
```lua
local minecart -- a minecart entity obtained somewhere
local badArrow = tolua.cast(minecart, "cArrowEntity")
-- cast will succeed; badArrow is a valid Lua object,
-- but an invalid C++ object
badArrow:SetIsCritical(true)  -- will most likely crash the server!
```

**Comment by madmaxoft** [comment]
Hah, the fix was really trivial. We had the ToLua package file contents in the wrong order.

**Comment by madmaxoft** [comment]
There, it should be all fixed.

**Comment by Seadragon91** [comment]
I'm sorry xoft. Now I get this stack trace, if I run the command `inh` from the debuggers plugin.
```
[17:34:37] LUA: Plugins/Debuggers/Debuggers.lua:1671: error in function 'GetEntityType'.
     argument #1 is 'cMonster'; 'const cEntity' expected.

[17:34:37] Stack trace:
[17:34:37]   [C](-1): GetEntityType
[17:34:37]   Plugins/Debuggers/Debuggers.lua(1671): (no name)
[17:34:37] Stack trace end
[17:34:37] Error in plugin Debuggers calling function <callback>()
```

**Comment by madmaxoft** [comment]
How could you get a `cMonster` out of a projectile entity? Did you change the command handler?

**Comment by Seadragon91** [comment]
I didn't change anything. I compiled mc server from current source, enabled the debuggers plugin and called the command `inh`, that creates that stack trace. I also tested a build from `http://builds.cuberite.org/` and it creates it too.

**Comment by Seadragon91** [comment]
Found it.
`$cfile "../Mobs/Monster.h"` inherits from cEntity, but the line is before the `$cfile "../Entities/Entity`.
Moving the first line under the Entity.h linem, fixes it.
https://github.com/mc-server/MCServer/blob/master/src/Bindings/AllToLua.pkg#L66

**Comment by madmaxoft** [comment]
I fixed that, I hope that's all now.
