### ISSUE TITLE
Builds server offline?

### ISSUE THREAD

**Issue by fermino** [mc-server/MCServer#1793]
The download links gives me a timeout. 
Example: <http://builds.cuberite.org/job/MCServer%20Linux%20x86/lastSuccessfulBuild/artifact/MCServer.tar> (Or any in the main MC-Server page). 
Is the server down?

**Comment by bearbin** [comment]
The hosting provider appears to be down. Troubleshooting the issue.

**Comment by bearbin** [comment]
The buildserver should be coming back up in a minute or two.

**Comment by fermino** [comment]
Thanks :D
