### ISSUE TITLE
Add a way to send non-chat messages to the user

### ISSUE THREAD

**Issue by jan64** [mc-server/MCServer#1803]
Currently there is no way to send a non-chat message (system / above the action bar message) to the user. 
https://github.com/mc-server/MCServer/blob/master/src/Protocol/Protocol18x.cpp
Faulty lines are 235 and 252. 
It's hardcoded to 0, but there are 3 possible options: 
0: chat (chat box), 1: system message (chat box), 2: above action bar
( according to http://wiki.vg/Protocol#Chat_Message )

Also, i don't think there is any support for http://wiki.vg/Protocol#Title

**Comment by madmaxoft** [comment]
I think the proper solution would be to have multiple functions - one for chat, one for sysmessage, one for above action bar. This way if the protocol ever decides to implement the messages using completely different packets, our life will be easier. And if we decide to make these calls interceptable by plugins, then it will be easier as well.

The `/title` support has a separate issue: #1806

**Comment by jan64** [comment]
When implementing non-existent packets in the 1.7 protocol code, should i use a noop or a normal message?

**Comment by madmaxoft** [comment]
I think a noop is better, since the messages are likely to get updated quite often and that would spam the main chat too much if sent there.
