### ISSUE TITLE
Build is broken on OSX 10.10

### ISSUE THREAD

**Issue by jonfabe** [mc-server/MCServer#1815]
As of commit a8a2d3d504a84f26d71aa364a169963a70ce6288, the build fails on OSX with the error:

MCServer/src/FastRandom.cpp:13:1: error: thread-local storage is unsupported for the current target
thread_local unsigned int m_Counter = 0;
^

Reversing the referenced commit allows it to build and run without issue.

**Comment by tigerw** [comment]
Try the suggestion here: http://stackoverflow.com/questions/23791060/c-thread-local-storage-clang-503-0-40-mac-osx

(compile using `clang++ -stdlib=libc++ -std=c++11`)

**Comment by jonfabe** [comment]
No that does not work, infact if you try to pass those as command line arguments for the entire build it really breaks things, and trying to compile just that file with those arguments results in the same error. In fact, the referenced website itself says "Ok, this works for the normal clang version but not for the Xcode one."

**Comment by worktycho** [comment]
Since it looks like thread_local is completely broken on OS X at the moment we should probably fix it by falling back to __thread on OS X.

**Comment by madmaxoft** [comment]
I still don't quite understand why we need a thread-local variable for the random generator at all. Even if we use a single global variable and each thread butchers it for the other threads, it's a random value, so what?

**Comment by worktycho** [comment]
Because it is allowed for the program to crash on a race condition.

**Comment by madmaxoft** [comment]
Really? I can't believe that.

**Comment by madmaxoft** [comment]
I think the only undefined behavior is if we don't tell the compiler about the possible data race; if we mark the variable as `volatile`, then there should be no UB.

**Comment by worktycho** [comment]
`volatile` has nothing to do with race conditions. That's a common myth. `volatile` induces a memory barrier to optimizations, but does not introduce a hardware memory barrier, allowing race conditions. If you want a hardware memory barrier, you a have to go for std::atomic, but that may use mutexs which we want to avoid.

**Comment by madmaxoft** [comment]
But I keep saying, we don't need any kind of synchronization, only to avoid the compiler doing unexpected optimizations, which is exactly what `volatile` does. If two threads race on reading or writing the value, we don't care, as long as the program doesn't crash.

**Comment by worktycho** [comment]
And my point is that you still invoke UB, and that is allowed to cause a crash. As I said earlier, this may be somewhere where we want to make an additional assumptions about system architecture, beyond what is specified in the c++ standard.

**Comment by tigerw** [comment]
> __thread

The stack underflow post said that this is similarly broken.

**Comment by worktycho** [comment]
Then we have to use std::atomic on OS X, which should be lock free.

**Comment by jonfabe** [comment]
I will say using `__thread unsigned int m_Counter = 0;` rather than `thread_local unsigned int m_Counter = 0;` does work on osx 10.10, at least insofar as compiling and running in a brief test.

**Comment by snowyu** [comment]
compile passed on Mac via `__thread`.added, thanks:

```c
#ifndef thread_local
  #define thread_local __thread
#endif
```
