### ISSUE TITLE
Can't find a command to op players?

### ISSUE THREAD

**Issue by SpockMan02** [mc-server/MCServer#1835]
I wasn't able to find a command to make players ops (operators) from the console. Tried /op, op, /operator, operator, /admin, et cetera, looked at help list. Is there one?

**Comment by NiLSPACE** [comment]
By default MCServer doesn't have a command to give someone a different rank. If you have the Core plugin installed (Which is default) then you can use /rank.

**Comment by SpockMan02** [comment]
Oh.. It's a rank system. Okay.

**Comment by NiLSPACE** [comment]
Yes, MCServer has it build in ;)
