### ISSUE TITLE
Breaking leaves ALWAYS drops saplings

### ISSUE THREAD

**Issue by tonibm19** [mc-server/MCServer#1839]
Title says it.
It should be quite easy to fix (random?)

**Comment by NiLSPACE** [comment]
Might be a problem in the randomizer. I noticed I got the same world seed just a few minutes ago when I was searching for new seeds.

**Comment by NiLSPACE** [comment]
I don't think this is happening anymore. Could you confirm?

**Comment by bearbin** [comment]
Confirmed, doesn't happen.
