### ISSUE TITLE
cPlayer:MoveToWorld does not broadcast event

### ISSUE THREAD

**Issue by DevToaster** [mc-server/MCServer#1842]
When I was testing out a few of my plugins with some friends over LAN a day ago, we couldn't see each other when we were both moved to the same world using the cPlayer:MoveToWorld function.  I narrowed it down to this by using /portal.  Along with that, we could not pick up items after being moved.

**Comment by DevToaster** [comment]
Fixed in #1846

**Comment by NiLSPACE** [comment]
It's not merged yet ;)
