### ISSUE TITLE
Nether: no glowstones/glowdust

### ISSUE THREAD

**Issue by jammet** [mc-server/MCServer#1863]
It appears there is no glowstone or glowdust generated at all in the Nether at the moment.

**Comment by madmaxoft** [comment]
@NiLSPACE This is something for you, isn't it? A new clump-like generator :)

For each chunk, generate a few sets of XZ sizes, then for each set generate XYZ coordinates that will fit the XZ size within the chunk (thus forming a box that is completely inside the chunk), then check the top center block of this "box" if it has a solid block above an air block, and finally generate random glowstone within the box, possibly with the noise being more dense toward the top center of the box.

This way the generator will work with our per-chunk generating, and it will be even capable of generating glowstone in normal world, should anyone wish to set it up so.

**Comment by NiLSPACE** [comment]
I could sure as well try ^^
I was actualy working on the dungeonrooms generator to not generate above the composition.

**Comment by NiLSPACE** [comment]
How is this?:
![Img1](http://puu.sh/hjwsB/9601e98643.jpg)
![Img2](http://puu.sh/hjwwI/e66de9edef.jpg)

**Comment by jammet** [comment]
Looks ripe for picking! ;)

**Comment by SphinxC0re** [comment]
@jammet This sounds like a bug. You should open an issue for that

**Comment by NiLSPACE** [comment]
@SphinxC0re I think that is because the quartz block doesn't use the Ore blockhandler yet.

@jammet The glowstone blocks drop a few glowstone dusts like they should.
