### ISSUE TITLE
Clay ore blocks need to use the OreHandler

### ISSUE THREAD

**Issue by jammet** [mc-server/MCServer#1884]
At the moment, when a spade is used to dig up clay, you get the whole block instead of the ore, and you cannot make bricks as a result.

**Comment by jammet** [comment]
Would this be correct? Collecting Clay doesn't give you experience, only smelting it, does. And for each block you dig up, you will always get 4 clay (item).

case E_BLOCK_CLAY:
			{
				a_Pickups.push_back(cItem(E_ITEM_CLAY, (char)(4)));
				break;
			}

**Comment by madmaxoft** [comment]
No need to cast the `4` into a `char`.

**Comment by jammet** [comment]
So ... just this?

case E_BLOCK_CLAY:
			{
				a_Pickups.push_back(cItem(E_ITEM_CLAY));
				break;
			}

**Comment by madmaxoft** [comment]
No, that would drop just one clay. The `4` needs to stay but doesn't need the cast:
`cItem(E_ITEM_CLAY, 4)`

Also, please use triple-backward-apostrophes for quoting code (I've edited your comments to include them)

**Comment by jammet** [comment]
Triple ... I'll have to actually look that up. Thanks for the help, I made
a small patch again, hoping it's alright. And only because it is almost the
same as the prior. Clearly not made out for this kind of thing, but thank
you for all the patience.

**Comment by jammet** [comment]
I'm on the latest build, just a few hours old, and I'm stumped. I still only dig up the raw clay block, I don't get what the OreHandler should be giving me.

**Comment by NiLSPACE** [comment]
Did you give `E_BLOCK_CLAY` the proper BlockHandler in `BlockHandler.cpp`?

**Comment by jammet** [comment]
No. I don't know how, really.

**Comment by NiLSPACE** [comment]
You give the clay block by adding it in this list:https://github.com/mc-server/MCServer/blob/master/src/Blocks/BlockHandler.cpp#L180 With the proper block handler. The ore handler in this case.

**Comment by jammet** [comment]
Well, it sounds like an invitation to try this anyway. It does look rather
simple so, I'll did that then.
Too late to correct the embarrassing typo, but at least it's not in the
commit itself.

**Comment by jammet** [comment]
Good grief, why does this look all messed up outside of the editor. -.-

If there is someway to just do away with the change and try again? I don't
see how.
