### ISSUE TITLE
Trapdoors "forget" open/closed state upon server restart

### ISSUE THREAD

**Issue by jammet** [mc-server/MCServer#1887]
Many times they are used for decoration -

![2015-04-22_08 04 16](https://cloud.githubusercontent.com/assets/11940735/7268124/bf59d216-e8c5-11e4-80de-b384e69f6780.png) 

... and this is what it looks like when the state they were left in wasn't saved, or saved correctly.
Look at that sad little lantern.... ;) 

![2015-04-22_08 05 25](https://cloud.githubusercontent.com/assets/11940735/7268128/daf271ea-e8c5-11e4-87f3-4b2b1402e250.png)

**Comment by NiLSPACE** [comment]
I doubt the server just doesn't save it. Could you try setting the trapdoors to their open state (top picture) while someone else is watching? Does he see the trapdoors changing?

**Comment by jammet** [comment]
There wasn't anybody around atm, so I logged in twice on the same machine
with mine and my brothers accounts, so if that makes any difference, have
two instances of MC running on the same machine..
I could see myself flipping the trapdoors up and down in both MC windows.

I can do the test again when somebody else is on the servers later today,
too.

**Comment by Howaner** [comment]
Yeah, the redstone simulator is buggy.

**Comment by jammet** [comment]
I wasn't using any redstone.

**Comment by Seadragon91** [comment]
Can confirm the problem. Reproduce
1. Place a trapdoor, change the current state with right-click.
2. Stop the server
3. Start the server, relog in and it's has changed back

Looks like the state of the trapdoor, is not saved on shutdown of world.

**Comment by Howaner** [comment]
If you disable the redstone simulator, the problem is fixes.
So it's the redstone simulator :D

I already reported this problem 1 year ago.
But xoft (or tigerw?) closed the issue ...

**Comment by NiLSPACE** [comment]
This one?: #756

**Comment by Howaner** [comment]
oh, yes.
