### ISSUE TITLE
Dark oak logs don't work in the furnace

### ISSUE THREAD

**Issue by jammet** [mc-server/MCServer#1899]
You cannot use Dark oak logs as fuel in a furnace, no can it be burned into charcoal.

**Comment by jan64** [comment]
This should be a fairly simple fix.
Add to the smelting section:
162              = CharCoal # log2
And, to the fuel section:
! 162             = 300    # -> 15 sec (Log2)

**Comment by jammet** [comment]
Also, acacia logs do not burn, while planks do.
I won't add these suggested lines, however tempted. Enough messing up on my side. Hope someone else can do it proper.
