### ISSUE TITLE
Right click with item/block in hand on invalid block causes bogus right click event

### ISSUE THREAD

**Issue by Woazboat** [mc-server/MCServer#1908]
On right click with an item or a block in hand on a position that would normally do nothing, a bogus right click event is created. 
The coordinates are always {-1, 2047, -1}, the block face is always -1. The held item is correct. 
Tested with a debug build compiled from source.

For example, right click with a ladder on leaves: 
`[40f8250ae03b4926|20:36:19] HandleRightClick: {-1, 2047, -1}, face -1, HeldItem: 65:0:0 * 1; dist: 1984.01`

**Comment by NiLSPACE** [comment]
This is because Minecraft sends two packets. It sends one when you have a block in the hitbox, but it wil also **always** send a packet with the data you described. With other words, this is normal. It allows for example the right click compass tool for WorldEdit.

**Comment by Woazboat** [comment]
Ah, alright. Thanks for clarifying. In that case I'll just go ahead and close this again.
