### ISSUE TITLE
All placed blocks disappear after logout

### ISSUE THREAD

**Issue by SafwatHalaby** [mc-server/MCServer#1912]
I log in, place some blocks, destroy some other blocks, log out.
When I log in again, all blocks that I placed disappear, blocks that I destroyed seem to preserve state and they do not re-appear. 100% reproducible, client v1.7.2, Linux 64 bit, Master branch.

**Comment by wiseoldman95** [comment]
Just tested with 1.8.4, bug is not present there.

**Comment by NiLSPACE** [comment]
It probably came with #1686.

**Comment by madmaxoft** [comment]
I don't see the reported behavior with 1.7.2 WeCui client. and server at 011126293b42efad5ccbef912c44418c2437cf78. Has this been fixed already?

**Comment by SafwatHalaby** [comment]
I'll test it again.

**Comment by SafwatHalaby** [comment]
I cannot reproduce it, so some commit must have fixed it.
