### ISSUE TITLE
Some console commands are case sensitive to player names

### ISSUE THREAD

**Issue by SafwatHalaby** [mc-server/MCServer#1948]
Both `give safwat dirt` and `give Safwat dirt` work.
However, `clear safwat` does not work while `clear Safwat` works.

**Comment by madmaxoft** [comment]
This should be reported in the [Core](https://github.com/mc-server/Core) plugin, as that one's responsible for the commands.

**Comment by SafwatHalaby** [comment]
https://github.com/mc-server/Core/issues/135
