### ISSUE TITLE
Cake crafting dont give back the bucket

### ISSUE THREAD

**Issue by falkseidl** [mc-server/MCServer#1962]
When crafting a cake, players must use milk buckets, an egg, wheat and sugar.
In Vanilla it gives you the 3 buckets without milk back, but in MCServer the bucket is forever lost.

**Comment by madmaxoft** [comment]
Is there any crafting recipe in vanilla that consumes the entire fluid-filled bucket and doesn't give the bucket back? If there isn't, this special case should be hard-coded into the server - for any fluid-filled bucket, give the bucket back when crafting.

**Comment by jammet** [comment]
You also don't get the plate back when you eat stew, like mushroom stew.

I've looked at this for a while some weeks ago, and was hoping to fix it, when I found buckets weren't returned.

Was looking for something like
, return bucket
, return bowl

**Comment by madmaxoft** [comment]
I'm afraid this won't be solved with a simple change in crafting.txt, this will require new code to be written.

**Comment by fhntv24** [comment]
If i'm not mistacing, each MC item has container - its null , or for milk bucket its bucket item. Copy of that item should be added on crafting. Forge also adds onCrafting , idk if its vanilla code or not. 

Also there is no recipies that wont return bucket. I will maybe look into it , maybe i will fix that.

**Comment by nounoursheureux** [comment]
Fixed by #2210
