### ISSUE TITLE
AI - WouldBurnAt() assertion fail

### ISSUE THREAD

**Issue by SafwatHalaby** [mc-server/MCServer#1988]
![Imgur image here](http://i.imgur.com/hr55WdN.png).
I accidentally quit the terminal before copy-pasting, so only an image exists.

**Comment by madmaxoft** [comment]
Posted too soon :P

**Comment by SafwatHalaby** [comment]
Edited the post.

**Comment by SafwatHalaby** [comment]
Oh :P

**Comment by tigerw** [comment]
This is fixed, I think, in #1977.

**Comment by SafwatHalaby** [comment]
Yes, this must be the problem.

**Comment by tigerw** [comment]
Fixed via #1977 and #1991.
