### ISSUE TITLE
If inventory full, there appears an extra stack in enchantment table

### ISSUE THREAD

**Issue by falkseidl** [mc-server/MCServer#1993]
If player have a full inventory, and looks into the enchantment table, one item is in one of the enchantement slots. This happens also in survival gamemode.
Sometime there is a duplication of items.

Video: http://youtu.be/kdIfiwet0R0

**Comment by Woazboat** [comment]
Same as #2003. Already did a little research about this bug over there.

**Comment by bearbin** [comment]
Dupe of #2003, closing as more discussion is there.
