### ISSUE TITLE
Failed to authenticate account

### ISSUE THREAD

**Issue by falkseidl** [mc-server/MCServer#1998]
Almost every join onto my server is saying the player: 
```
[18:37:26] Cannot connect to sessionserver.mojang.com: Resource temporarily unavailable
[18:37:26] SecureRequest: Can't connect to sessionserver.mojang.com: 
[18:37:26] Kicking player Fynn_W for "Failed to authenticate account!
```
Sometimes it works immediately, sometimes comes this error 1 times but also up to 3 times.
I do not think it is up to the servers of Mojang, because it occurs since I discovered MCServer.
But this only happens on my banana pi and cubieboard. If the server is started on the PC, then not.

Does anyone have any idea why this happens, maybe someone can add an option to set the timeout or so.

**Comment by bearbin** [comment]
This seems to me very much like a temporary mojang error. The session servers are very unreliable. 

Perhaps a solution would be to retry if we get an error rather than just failing.

**Comment by bearbin** [comment]
Is this still happening?

**Comment by falkseidl** [comment]
Yes, also with the newest self compiled testing build.

**Comment by bearbin** [comment]
Can you try with the Mojang server on your bananapi/cubieboard and see if the same thing happens?

Also, can you do `ip -s a` on your bananapi/cubieboard and report the results?

**Comment by falkseidl** [comment]
This is the output:

```
[management@motschegiebchen ~]$ ip -s a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 16436 qdisc noqueue state UNKNOWN group default 
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
    RX: bytes  packets  errors  dropped overrun mcast   
    1676       16       0       0       0       0       
    TX: bytes  packets  errors  dropped carrier collsns 
    1676       16       0       0       0       0       
2: tunl0: <NOARP> mtu 1480 qdisc noop state DOWN group default 
    link/ipip 0.0.0.0 brd 0.0.0.0
    RX: bytes  packets  errors  dropped overrun mcast   
    0          0        0       0       0       0       
    TX: bytes  packets  errors  dropped carrier collsns 
    0          0        0       0       0       0       
3: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UNKNOWN group default qlen 1000
    link/ether 02:98:09:83:23:2a brd ff:ff:ff:ff:ff:ff
    inet 192.168.0.55/24 brd 192.168.0.255 scope global eth0
    inet6 fe80::98:9ff:fe83:232a/64 scope link 
       valid_lft forever preferred_lft forever
    inet6 fe80::52b3:a4a8:c179:f53f/64 scope link 
       valid_lft forever preferred_lft forever
    RX: bytes  packets  errors  dropped overrun mcast   
    51293      366      0       0       0       0       
    TX: bytes  packets  errors  dropped carrier collsns 
    49162      295      0       0       0       0       
```

I try now to start the java server, but I'm not sure if its starting up this time, or how long it takes.

**Comment by bearbin** [comment]
I think the problem is most likely that the session servers have a misconfigured ipv6 record and MCServer is prioritising ipv6 over ipv4.

**Comment by falkseidl** [comment]
![java](https://cloud.githubusercontent.com/assets/5732964/7666978/eeb06204-fbf9-11e4-8bdc-85a50d3f12bc.png)

it takes soooo long -.-

**Comment by falkseidl** [comment]
After ca. 30 minutes the server is ready, and the result is that the server is crashing if a player joins, I will try it again a few times, but don't think that I get it working.

**Comment by bearbin** [comment]
Did you get an error message when it crashed?

**Comment by falkseidl** [comment]
It didnt respond anymore, not in the console and not the ping from the serverlist ingame.

**Comment by falkseidl** [comment]
I will try it again, if I don't need the cubieboard, because the server needs really long to start up, also adding more ram with -Xmx doesn't improve the startup time.

**Comment by bearbin** [comment]
Does the PC you were using MCServer on use windows or Linux?

**Comment by falkseidl** [comment]
Linux Fedora 21

**Comment by bearbin** [comment]
Can you do `ip -s a` on your PC then as well?

**Comment by falkseidl** [comment]
Yes of course:

```
[ich@faultierfarm ~]$ ip -s a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default 
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: enp3s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 08:60:6e:d8:8c:c7 brd ff:ff:ff:ff:ff:ff
    inet 192.168.0.14/24 brd 192.168.0.255 scope global dynamic enp3s0
       valid_lft 568811sec preferred_lft 568811sec
    inet6 2a00:c1a0:4800:c700::42/128 scope global dynamic 
       valid_lft 52sec preferred_lft 22sec
    inet6 2a00:c1a0:4800:c700:a60:6eff:fed8:8cc7/64 scope global noprefixroute dynamic 
       valid_lft 1209599sec preferred_lft 1209599sec
    inet6 fe80::a60:6eff:fed8:8cc7/64 scope link 
       valid_lft forever preferred_lft forever
3: virbr0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default 
    link/ether 52:54:00:db:f0:15 brd ff:ff:ff:ff:ff:ff
    inet 192.168.122.1/24 brd 192.168.122.255 scope global virbr0
       valid_lft forever preferred_lft forever
4: virbr0-nic: <BROADCAST,MULTICAST> mtu 1500 qdisc pfifo_fast master virbr0 state DOWN group default qlen 500
    link/ether 52:54:00:db:f0:15 brd ff:ff:ff:ff:ff:ff
```

**Comment by bearbin** [comment]
Hmm. I don't know if you can blame it on IPv6 then, the PC has it as well.

**Comment by falkseidl** [comment]
I've disabled IPv4 now, and it's working fine on the pc.

![ipv4](https://cloud.githubusercontent.com/assets/5732964/7667385/b032f4cc-fc05-11e4-82ef-d6b2fad40b9b.png)

**Comment by bearbin** [comment]
I doubt this would work, but could you disable IPv6 on the pi?

**Comment by falkseidl** [comment]
Yay! It's working perfectly :D

I created the file "/etc/sysctl.d/40-ipv6.conf"
and wrote in:
```
net.ipv6.conf.all.disable_ipv6 = 1
net.ipv6.conf.*NETWORKINTERFACE*.disable_ipv6 = 1
```

**Comment by falkseidl** [comment]
But, would be nice, if it's working also with IPv6. Because for some actions it is needed.

**Comment by bearbin** [comment]
There must be some difference in configuration between the computer and the pi, that is causing the issues.

But for now the issue is solved, and since it works fine on the pc it's not a mcserver issue.
