### ISSUE TITLE
Wolves going under water

### ISSUE THREAD

**Issue by falkseidl** [mc-server/MCServer#2014]
I've noticed for some time now, that wolves like it to go underwater. Especially they like it, to standing in 1 block deep water and go around or standing still for some time. Actually, they should drown, or go not into water.

**Comment by SafwatHalaby** [comment]
Patience will solve this, the AI and pathfinder are undergoing a big change.
[PathFinder status](http://forum.mc-server.org/showthread.php?tid=1571).
[Mob status](http://forum.mc-server.org/showthread.php?tid=1895.

**Comment by SafwatHalaby** [comment]
The general issue is that short mobs have trouble with water. This is identical to #1064

**Comment by bearbin** [comment]
Yep, dupe of #1064.
