### ISSUE TITLE
Seed the MTRand/cFastRandom seed counter with a true random number

### ISSUE THREAD

**Issue by worktycho** [mc-server/MCServer#2021]
At the moment their is very little entropy in our world seeds because it is based off this counter.

**Comment by SphinxC0re** [comment]
You can only really achieve this on Linux. /dev/random does cryptographic true-random. On Windows it is not that safe

**Comment by jan64** [comment]
i believe you can get relatively good sources of randomness on windows using cryptoapi.

**Comment by bearbin** [comment]
We don't actually need a true random number, even seeding with the current time would be better than what we have ATM, I think,

**Comment by jan64** [comment]
afaik, cpp11 provides std::random_device as architecture independent source of randomness, the issue here is that not all compilers implemented it yet on all platforms.

**Comment by tigerw** [comment]
Current time works also.

**Comment by madmaxoft** [comment]
Since MTRand and cFastRandom are used only for the random game events, there's not much point in seeding them with anything stronger than current time.

**Comment by worktycho** [comment]
I don't mind seeding the counter off the time, just don't initialise the generators with the time.

**Comment by bearbin** [comment]
There is no entropy in our world seeds at the moment.

I created one world on a remote server, using a pre-compiled build. (just by starting the server)

I then created a world on my own PC using a self-compiled build and I got exactly the same world. (just by starting the server)
