### ISSUE TITLE
Crafting issues.

### ISSUE THREAD

**Issue by bearbin** [mc-server/MCServer#2035]
I encountered various issues with crafting. 

I first tried drag-to spread and spread out my wood planks around the mini crafting slot in the player window. On the client side this appeared to work, but upon trying to get the crafting result it failed.

Then I tried manually right-clicking with the planks in all of the boxes. Upon clicking on the result, it produced 4 sticks instead of the expected crafting table, while still using the original amount of wood.

Finally, I tried the method in the paragraph above again, and it did produce a crafting table and I placed the table in my inventory. When I pressed escape to exit the window, another crafting table was dropped on the ground in front of me, but upon a relog the dupe was fixed.

**Comment by madmaxoft** [comment]
@tigerw broke this in c10e83c02d7074cde10200842451646ecca21ca6

**Comment by bearbin** [comment]
I can confirm the issue is fixed.
