### ISSUE TITLE
Cows are one-hit kills.

### ISSUE THREAD

**Issue by bearbin** [mc-server/MCServer#2042]
Cows and only cows only take one hit to kill. Newly generated land and old land alike.

**Comment by NiLSPACE** [comment]
This is pretty random, some servers have it and some don't. I think @Seadragon91 doesn't have it.

**Comment by SafwatHalaby** [comment]
Thought you could have multiple milestones. Sorry.

**Comment by Seadragon91** [comment]
Did you already looked into the monsters.in?

**Comment by bearbin** [comment]
This is using the default monsters.ini, and no other monsters are affected apart from cows.

**Comment by bearbin** [comment]
In fact, this seems more complicated than at first. After staying in one area for a while, the cows take more than one hit to kill. Perhaps worldgen cows take 1 hit and spawned ones take more?
