### ISSUE TITLE
Torches can't be placed on fences.

### ISSUE THREAD

**Issue by NiLSPACE** [mc-server/MCServer#2050]
As the title says you can't place torches on fences. The same applies to cobblestone walls, glass and stained glass. You can only place torches on the top of these blocks.

**Comment by tigerw** [comment]
Are you sure? Torches appear to be placeable on the top of fences.

**Comment by bearbin** [comment]
I can't replicate this bug either.

**Comment by bearbin** [comment]
I think NiLSPACE meant on the side of fences. I'm not sure if that's even a vanilla feature.

**Comment by NiLSPACE** [comment]
When I tried placing torches on your dev server I couldn't do it. It is possible that the inventory was out of sync, and that's why it didn't work.

**Comment by NiLSPACE** [comment]
No, I meant the top of the fence.

**Comment by bearbin** [comment]
Well I can place torches on the top of fences fine on the dev server.

**Comment by jammet** [comment]
You cannot put torches ontop of fences made from some of the woods. You oakfence is fine. It definitely doesn't work if your fence is made from acacia.

**Comment by NiLSPACE** [comment]
Oh, now it makes sense. I tried placing it on a birch fence.

**Comment by jammet** [comment]
You should be able to put one on any of these of course.

**Comment by NiLSPACE** [comment]
Yeah, but I only tried placing it on a birch fence ;)
