### ISSUE TITLE
Trying to cross-compile - tolua

### ISSUE THREAD

**Issue by netomx** [mc-server/MCServer#2055]
Hi! I am cross-compiling it to MIPS, and I have a problem with tolua, as it compiles as my target processor, but I see that you make tolua a binary to compile other things... how can I compile tolua as the host machine to continue the cross-compilation? Thanks!

**Comment by bearbin** [comment]
You should just be and to copy in a tolua from a regular build on your
computer and it should work.

**Comment by netomx** [comment]
Thanks, you're right. I've compiled tolua++ and it worked until tolua++ execution. It doesn't output the file Bindings.cpp . Will try to debug on another VM

**Comment by netomx** [comment]
I finished up making another VM, compiling for x32, then scp the Bindings folder to the other one. Built perfectly, but it needs more RAM than my RT5350's 32MB can offer :(

**Comment by NiLSPACE** [comment]
Yes, I'm afraid so. MCServer uses around 50 mb when it starts, and for each player about 50 mb extra.
