### ISSUE TITLE
Can't get seeds from tall grass

### ISSUE THREAD

**Issue by tonibm19** [mc-server/MCServer#2063]
To reproduce:
-Break all the tall grass you can, you won't get any seeds,

**Comment by Rakete1111** [comment]
Can't reproduce in Survival, but in Creative this happens, though I don't know if that's a feature or not

**Comment by NiLSPACE** [comment]
Maybe he means double tall grass?

**Comment by tonibm19** [comment]
I mean on 1 block-high tall grass.
It was in bearbins dev server

**Comment by NiLSPACE** [comment]
It worked fine for me. I now even have a semi-automated farm ;) How could I have gotten the first seed ;)

**Comment by LO1ZB** [comment]
I get seed from gras, the change is somethling like 1/20 - 1/30

**Comment by tonibm19** [comment]
Closed then
