### ISSUE TITLE
Cows spawn in oceans

### ISSUE THREAD

**Issue by jammet** [mc-server/MCServer#2080]
It should probably be squids and other sea mobs, but when I fly across large ocean biomes, I see the server spawning groups of cows all over the place, instead.

**Comment by SafwatHalaby** [comment]
Lol

**Comment by programmerq** [comment]
I was trying MCServer for the first time this evening. I noticed the same thing, came to report it, found this issue.

**Comment by SuperSpyTX** [comment]
Maybe you might be looking at SeaCows, a recently added animal.

**Comment by SafwatHalaby** [comment]
Accident.
