### ISSUE TITLE
settings.ini is not correct anymore

### ISSUE THREAD

**Issue by Seadragon91** [mc-server/MCServer#2082]
Hey,

Tried my server and was confused my no plugins has been loaded. In server console was written `0 plugins loaded`. Looked into the settings.ini and didn't found see the section [Plugins]. Added it to the file and restarted the server, now the plugins has been loaded. Stopped the server and restarted it and a few restarts later. The settings.ini has now that content.
Tested a build from the build website, same problem.

```
--- snipped ---
[Plugins]
; Plugin=Debuggers
; Plugin=HookNotify
; Plugin=ChunkWorx
; Plugin=APIDump
; Plugin=Debuggers
; Plugin=HookNotify
; Plugin=ChunkWorx
; Plugin=APIDump
; Plugin=Debuggers
; Plugin=HookNotify
; Plugin=ChunkWorx
; Plugin=APIDump
; Plugin=Debuggers
; Plugin=HookNotify
; Plugin=ChunkWorx
; Plugin=APIDump
Plugin=Core
Plugin=TransAPI
Plugin=ChatLog
Plugin=Core
Plugin=TransAPI
Plugin=ChatLog
Plugin=Core
Plugin=TransAPI
Plugin=ChatLog
Plugin=Core
Plugin=TransAPI
Plugin=ChatLog

[Worlds]
DefaultWorld=world
World=test

[Plugins]

[DeadlockDetect]
Enabled=1
IntervalSec=20

[Plugins]

[Plugins]

[Plugins]
```

**Comment by Shadowraix** [comment]
I can confirm this. This happened to me when updating to build #270 Windows x64

**Comment by bearbin** [comment]
I think this is a problem with @worktycho's new code, and I think this issue may be a dupe.

**Comment by worktycho** [comment]
Coverity has found a few issues with my code that might be causing this.

**Comment by bearbin** [comment]
@worktycho How are you getting on with fixing those issues?

**Comment by madmaxoft** [comment]
I don't think this is a Coverity-level bug, it's a bug in the logic itself.
