### ISSUE TITLE
Feature request: dynamic MOTD 

### ISSUE THREAD

**Issue by jammet** [mc-server/MCServer#2087]
As it is now, motd.txt is read once when the server starts, and every time you wish to change something about it, the server needs to be stopped and started again so the changed motd.txt is being re-read and shown to connecting players.

I'd like to see just make adaptations to the motd.txt on the fly, instead.

**Comment by NiLSPACE** [comment]
I think this can be done using plugins right? Wasn't there an API for it already?

**Comment by jan64** [comment]
I believe motd.txt is handled by Core, so it should be rather trivial to write a replacement plugin / use reload every time you change the motd.

**Comment by NiLSPACE** [comment]
No, he doesn't mean that motd. There is also the server description, and I think he means that.

**Comment by jan64** [comment]
I wrote a simple plugin utilizing that for a random motd: https://github.com/jan64/RandomDescription
It should be fairly simple to replace random motd with a static one, so that you can use reload to get a new one.

**Comment by jammet** [comment]
What I've meant is the text, the game shows you after you entered the world.
The default is something like "/help to see all the commands".

I edit that fairly frequently with news and changes.

The server description is what you see when you browse the server list, right? That's static in my case, and never changes. Just the name of the server. "Lonely Island".

**Comment by NiLSPACE** [comment]
Oh, so you **did** mean that. You don't have to restart the whole server for that. Just reload it since it's handled in the Core.

**Comment by jammet** [comment]
The NoChunkLoad plugin says terrible things will happen if I reload. ;)
Kinda stuck there. Thanks though. ..

**Comment by NiLSPACE** [comment]
That's something NoChunkLoad should fix, not Core in my opinion.

It most certainly isn't something MCServer should fix, so I'm closing this issue ;)

**Comment by jammet** [comment]
I meant of course NoChunkFall, but yeah, I agree.

**Comment by madmaxoft** [comment]
You could `unload` and re-`load` just the Core plugin:
```
unload Core
load Core
```
