### ISSUE TITLE
Add the cause of death parameter in the HOOK_KILLING to the API documentation

### ISSUE THREAD

**Issue by jan64** [mc-server/MCServer#2088]
~~Currently, it's not possible to get the cause of death using HOOK_KILLING.
(There is a workaround - using HOOK_TAKE_DAMAGE and comparing that to entity health, but that's ugly)~~

**Comment by NiLSPACE** [comment]
When looking at the C++ code where the hook is called it also gives the TakeDamageInfo to the hook. (https://github.com/mc-server/MCServer/blob/6bafff056038ca5909343b454318ea3dc15c0793/src/Entities/Entity.cpp#L737). Maybe it isn't in the documentation. Could you check if the hook actualy receives the TakeDamageInfo as a third parameter?

**Comment by Seadragon91** [comment]
I tested it, the TDI variable is passed to the api, this should be fixed.
Another problem is the if I print the `eDamageType` I only get numbers and not the enum value is that normal?
https://github.com/mc-server/MCServer/blob/master/src/BlockID.h#L997

**Comment by bearbin** [comment]
The enum values bit is. Enum values are just aliases for numbers, they are stored as numbers underneath to save on storage space.

**Comment by Seadragon91** [comment]
Ah now I know what I forgot to ask. I miss a list of the DamageType in the api.

**Comment by madmaxoft** [comment]
http://mc-server.xoft.cz/LuaAPI/Globals.html#DamageType
