### ISSUE TITLE
After crafting a hoe, the ingredients for a shovel are left in the crafting window.

### ISSUE THREAD

**Issue by bearbin** [mc-server/MCServer#2096]

**Comment by nounoursheureux** [comment]
This happens because of the asterisk * in the recipe: I replaced it with 1 and it worked properly. There must be something wrong in the parsing of the recipes

**Comment by madmaxoft** [comment]
But then the mirror image for the recipe shouldn't work.

**Comment by nounoursheureux** [comment]
No, it doesn't work. It is just the proof that the bug was caused by the asterisk.
We could do the same thing as the axe: use two lines per recipe.

**Comment by madmaxoft** [comment]
I'll track this in a debugger, it seems more involved than just an asterisk problem.
