### ISSUE TITLE
cWorld:TryGetHeight IsValid is a number

### ISSUE THREAD

**Issue by NiLSPACE** [mc-server/MCServer#2099]
cWorld:TryGetHeight returns 1 when valid, and 0 when false. Because of this you can't use
```lua
if (IsValid) then
   -- stuff
end
```

**Comment by bearbin** [comment]
Is this just a case of changing the data types in this function:

https://github.com/mc-server/MCServer/blob/43fecf48e3b1870e5de42d61fd3749fdbdc9bd0c/src/Bindings/ManualBindings_World.cpp#L503

Or does tolua require something more complicated than that?

**Comment by NiLSPACE** [comment]
I'm guessing that [this](https://github.com/mc-server/MCServer/blob/43fecf48e3b1870e5de42d61fd3749fdbdc9bd0c/src/Bindings/ManualBindings_World.cpp#L533) line has to change to.
 ```cpp
L.Push(res ? true : false);
```
but I'm not sure.

**Comment by bearbin** [comment]
Since res is already a bool, it should be possible to just push it without a conditional.

**Comment by NiLSPACE** [comment]
But it doesn't push res. If res is true it pushes 1, otherwise it pushes false.

**Comment by NiLSPACE** [comment]
Oh, yes that should work as well.
