### ISSUE TITLE
Travis CI is only compiling with Clang

### ISSUE THREAD

**Issue by SafwatHalaby** [mc-server/MCServer#2105]
Title says it all.

**Comment by Seadragon91** [comment]
Whats the problem, with that?

**Comment by bearbin** [comment]
Clang could fail and GCC succeed. 

ATM we compile in debug mode and release. It would be more worth it to compile in gcc and clang, both release.

blame @worktycho

**Comment by SafwatHalaby** [comment]
You mean: "Clang could Succeed and GCC fail"

**Comment by bearbin** [comment]
Yes :P

I did mean that.

**Comment by tigerw** [comment]
GCC has never failed where Clang succeeded though. It is why the CI was made to compile only with Clang, and GCC for Coverage builds only, though they might have been removed.

**Comment by bearbin** [comment]
It's good to check though, it's entirely possible that GCC will fail and clang succeed in the future, even if it has never happened in the past.

**Comment by madmaxoft** [comment]
We did remove all those compilers for a reason - the CI builds took forever. Now that gcc is added in again, they again take a lot of time.

**Comment by bearbin** [comment]
I think we could drop testing release/debug mode, one of them failing and not the other likely than just one compiler failing.

**Comment by worktycho** [comment]
No its more important to test debug/release. What clang accepts is basically a subset of what gcc accepts and differences are rare, whereas we have a lot of conditional code that only fires in debug.
