### ISSUE TITLE
How to autoload plugins on server start

### ISSUE THREAD

**Issue by PIC-27** [mc-server/MCServer#2109]
Hi,
Like the title say, i would like to have my server load all/or a list of plugin on start but i don't figure out how to do it.

**Comment by bearbin** [comment]
The plugins that are automatically loaded are specified in the settings.ini file. 

In the `[Plugins]` section, set `Plugin=YourPluginName` to have it auto loaded on server start. You can have as many `Plugin=...` entries as you like.

**Comment by madmaxoft** [comment]
Currently this is a bit broken - #2082

**Comment by bearbin** [comment]
According to the issue adding the plugins to the file still loads them, right?

**Comment by bearbin** [comment]
@PIC-27 Is this solved?

**Comment by PIC-27** [comment]
Thank you it works. Just in the default settings.ini the [plugin] section is not here by default, i think it would be better to have it by default .

**Comment by bearbin** [comment]
It is supposed to be in there by default but @worktycho broke it. A fix should be on it's way soon.
