### ISSUE TITLE
Error trying to drop item

### ISSUE THREAD

**Issue by PIC-27** [mc-server/MCServer#2111]
I'm trying to break a block and drop it as item but doesn't work
The function `destroyBlock` is called when a player break a block with the hook : `HOOK_PLAYER_BROKEN_BLOCK`
```lua
function destroyBlock(bx, by, bz)
	upperID = WORLD:GetBlock(bx, by, bz)
	if upperID == 17 or upperID == 162 then
		WORLD:DigBlock(bx, by, bz)
		local drop = cItems():Add(upperID, 1, 0)

		WORLD:SpawnItemPickups(drop, bx, by, bz, 0)
	end
end
```

It tells me ` argument #2 is 'nil'; 'value' expected.` in function `SpawnItemPickups`

**Comment by bearbin** [comment]
I think it's supposed to be `cItem`, not `cItems`

**Comment by PIC-27** [comment]
No, i tried it but it say `attempt to call method 'Add' (a nil value)`

**Comment by bearbin** [comment]
Sorry, I think what it should actually be is this:

```
local drop = cItems():Add(cItem(upperID, 1, 0))
```

**Comment by PIC-27** [comment]
Get the same error as my first try

**Comment by bearbin** [comment]
And you're sure that you're calling the function with non-nil x, y and z coords?

**Comment by PIC-27** [comment]
Yeah sure, that was the first thing i checked

**Comment by bearbin** [comment]
Hmm, may be a bug in the API. 

Also, are you reusing that WORLD var over multiple ticks?

**Comment by PIC-27** [comment]
Yeah i set up the var in the plugin Init function `WORLD = cRoot:Get():GetDefaultWorld()`

**Comment by madmaxoft** [comment]
`cItems:Add()` doesn't return any value, so your initial code assigned a `nil` into the `drop` variable.
Note that your "fixed" code creates a `drop` variable, sets it to `nil` and doesn't use it either.
