### ISSUE TITLE
cLineBlockTracer::Trace doesn't respect input vector boundaries

### ISSUE THREAD

**Issue by Rakete1111** [mc-server/MCServer#2161]
If I understand the Trace function properly, you give it 2 vectors and then it does something based on OnNextBlock. But the vector boundaries given in the Trace function aren't being respected, which is the cause of #2059. There is also a lot of unused variables in the function.
Is this intentional?
EDIT: added info

**Comment by madmaxoft** [comment]
Wait, what? That used to work perfectly. And which variables are not used? What tool's report are you using?

**Comment by Rakete1111** [comment]
Oh wait, nevermind, they are used :)
But the function still isn't working properly

**Comment by NiLSPACE** [comment]
We need more info. Why isn't it working properly? With what code isn't it working properly?

**Comment by Rakete1111** [comment]
The 2 vectors that I give to Trace for the bucket placement test are ok. But even though the length between those 2 vectors is only ~5 blocks, Trace doesn't stop when it reaches the end of the second vector. This could be an error on my side, but I think the Trace function doesn't respect those boundaries.
The 2 vectors are defined like so:
`a_Player->GetEyePosition()` and `a_Player->GetEyePosition() + (a_Player->GetLookVector() * BlockReach))`

**Comment by madmaxoft** [comment]
You're right, I added a test to the Debuggers plugin and it does walk a few blocks past the destination block. I'll look at it more.

**Comment by madmaxoft** [comment]
Yay, found the problem pretty easily :)
