### ISSUE TITLE
Service support broken on Windows

### ISSUE THREAD

**Issue by birkett** [mc-server/MCServer#2181]
With the addition of the TCLAP library to handle command line parameters, Windows service support is broken.

Starting the executable with "/service" on the command line, results in an unhanded exception while parsing the command line.

I'm working on a fix, and will issue a PR later today.

**Comment by bearbin** [comment]
What happens if you use linux-style switches?

**Comment by birkett** [comment]
TCLAP doesn't seem to like anything other than a single character in the switch names. Swapping the service to use -d instead of /service.

Also, lets ignore unmatched parameters with CmdLine::ignoreUnmatched. That will stop the exceptions being thrown with unknown parameters, and just ignore them instead.
