### ISSUE TITLE
Windows server included debug .cmd(s) fail

### ISSUE THREAD

**Issue by warmist** [mc-server/MCServer#2184]
There is no such flag /cdg /cdf
Exact message:

    D:\Games\mcserver>MCServer /cdf
    PARSE ERROR: Argument: /cdf
             Couldn't find match for argument

**Comment by madmaxoft** [comment]
I suppose you're using the x64 builds? Those don't have the option, true.
I think the best solution would be to add the option to all builds and each platform either use it or ignore it (if not supported)

**Comment by warmist** [comment]
Ah yes, 64bit, forgot to mention that.
