### ISSUE TITLE
Physics ignores signs.

### ISSUE THREAD

**Issue by SafwatHalaby** [mc-server/MCServer#2192]
In vanilla, chickens do not fall through this, but eggs do.

**Comment by NiLSPACE** [comment]
If I'm correct the chickens swim in water above the signs right?

**Comment by SafwatHalaby** [comment]
An image is missing, something went wrong with upload. 1 moment.

**Comment by SafwatHalaby** [comment]
https://imgur.com/a/WjGPg

**Comment by SafwatHalaby** [comment]
These two setups should trap chickens, but not eggs.
In MCServer, they trap nothing and the chickens fall down.

**Comment by NiLSPACE** [comment]
And in vanilla that does work? I kinda doubt it :|

**Comment by bearbin** [comment]
I also doubt it. If there was water above the signs it should trap chickens, but without it shouldn't do anything.

**Comment by SafwatHalaby** [comment]
I always use this in Vanilla to create a device which outputs eggs and keeps the chickens up there.

**Comment by SafwatHalaby** [comment]
I'll double-check.

**Comment by SafwatHalaby** [comment]
Yes, in vanilla this only works when there's water.
