### ISSUE TITLE
Placing water creates multiple water sources

### ISSUE THREAD

**Issue by jammet** [mc-server/MCServer#2222]
I'm redoing my old melon farm and I've just noticed this behaviour:

Created a 1-block hole in the ground.
Accidentally placed water on the *side* of it instead of the bottom.

What I got was a water source 2 blocks above the ground, and another one right next to it.

Tried it again - works every time.

**Comment by madmaxoft** [comment]
Could you make a picture so that it's easier for us to follow?

**Comment by jammet** [comment]
My apologies. This was made at the time when I wasn't sure about what was going on with the melons. I  believe I have seen the water flow over the invisible melons, giving me the false impression that for each 1 bucket of water I emptied, I got 2 blocks of water:

1 where I actually aimed for
1 more ontop of an invisible melon adjacent to that. 

This created a "floating" wave of water.
