### ISSUE TITLE
[Plugin causing server to crash]

### ISSUE THREAD

**Issue by Taugeshtu** [mc-server/MCServer#500]
Hi there. Found two nice ways to crash-a-server (in case you'll need one in the future, or maybe you'll put up a warning to such a case)

First:
Try cRoot:Get():GetDefaultWorld():GetName() inside Initialize()
Why crash:
Because world wasn't even loaded yet.
What could be done:
If plugin tries to access data which wasn't initialized - send a console message and roll the plugin.

Second:
Setup is a bit more complicated, but it's much more fun.
You're going to need two plugins. For instance I'll call them Handy and Coiny.
Now, Handy was put in front of Coiny in settings.ini, so it got loaded first.
After that, expecting such a setup, Coiny was initialized, and during that process Coiny got a reference to Handy (who's already there).

That's when it gets interesting. OnDestroy() Coiny is trying to save his coins, but he needs Handy's help in order to do so. But because Handy was first to arrive to party, he's already unloaded on a couch with a pack of beer. That's how you get a null ref, and it's all fun and games until Big Party Host Server doesn't come up and says "Segmentation fault" instead of traditional "nil value".
What could be done:
There are few options here. First being - let's unload plugins in reverse order! This way we can kind of make "dependencies", so if A is the base, B requires A to operate and C requires B, then we load A->B->C - and all good, and we unload C->B->A. When a plugin needs another plugin - other plugin is right there.
That, however, raises a question about cross-references. What if A depends on B, and B depends on A. Well, then they can't have init/destroy dependencies, because unparalleled Lua execution, quantum physics, coconut - you name it.
Second goes further with that concept - why don't we split out [Plugins] section out of Settings.ini? We'll have plugins.ini with something like:

[Core]
InitPriority=-100
DestroyPriority=100600

[Handy]
InitPriority=-90
DestroyPriority=100

Third option is to fix the crash (because plugins unload before world saving, this will lead to bizzare results) and put a warning.

P.S.
As you can see, both crashes happen at extremum cases. And yes, they both lead to "SegmentationFault". Perhaps, "crash on restart" is related to that and is actually tied up to plugins configuration.

**Comment by madmaxoft** [comment]
Closing as fixed:
- `cRoot:Get():GetDefaultWorld():GetName()` inside `Initialize()` has been fixed, it works now.
- Plugin calls have been made safe by using the plugin name as a string, instead of the plugin reference (`cPluginManager:CallPlugin()` API)
