### ISSUE TITLE
Deadlock on Debian7 64-bit - initial lighting

### ISSUE THREAD

**Issue by madmaxoft** [mc-server/MCServer#584]
I've just noticed the server deadlock once while it was processing the initial lighting. It would hang and report "1 chunk remaining to light" every 2 seconds. A kill and a restart seems to have fixed the issue, yet there seems to be a possibility of such a deadlock, so we should investigate it later on.

**Comment by bearbin** [comment]
Close? No further reports have been made, and the issue is a year and a half out of date.

**Comment by SafwatHalaby** [comment]
That depends on whether or not the current lighting code is the same lighting code of a year and a half ago.

**Comment by madmaxoft** [comment]
The lighting code itself hasn't changed, but the driver code that calls it has, and I haven't seen a single deadlock since then.
